### PR TITLE
Modify `mc/price-benchmarks` data processing

### LINKED ISSUE #2907: Modify `mc/price-benchmarks` data processing
### Describe the bug:
Following #2890, it's clear that the way the `PriceBenchmarksController` processes response data from the `MerchantPriceBenchmarks` controller does not match the way the QueryInterface will return results.

### Steps to reproduce:

1. Use instruction from #2890 to set up the test-proxy to mock API responses
2. Send a GET request to the `/wc/gla/mc/price-benchmarks/` endpoint
3. Review the response returned from the price-benchmarks endpoint

### Expected behavior:
The response should include data from the mocks in the expected shape:

```json
[
    {
        "product": {
            "id": 0,
            "thumbnail": "",
            "title": null
        },
        "effectiveness": "",
        "regular_price": 0,
        "price_on_google": 0,
        "price_gap": 0,
        "suggested_price": "",
        "predicted_clicks_change": "",
        "predicted_conversions_change": ""
    }
]
```

### Actual behavior:

An empty object is returned because the mock data isn't being processed correctly.

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
### Changes proposed in this Pull Request:

Closes #2907.

_Replace this with a good description of your changes & reasoning._

### Screenshots:

After the proxy tests:
**Response of `mc/price-benchmarks`:**
Screenshot 2025-05-14 at 9 03 00 PM

**Response of `mc/price-benchmarks/103572`:**
Screenshot 2025-05-14 at 9 03 26 PM

### Detailed test instructions:

1. Use instruction from #2890 to set up the test-proxy to mock API responses
2. Send a GET request to the `/wc/gla/mc/price-benchmarks/` endpoint
3. Review the response returned from the price-benchmarks endpoint

### Changelog entry

>

### CODE REVIEW

File: src/API/Google/MerchantPriceBenchmarks.php [hunk 1]
```diff
@@ -77,8 +94,28 @@ public function get_price_insights( array $args ): array {
...
+					'id'                               => $price_insights_result->getProductView()->getId(),
+					'offer_id'                         => $price_insights_result->getProductView()->getOfferId(),
+					'title'                            => $price_insights_result->getProductView()->getTitle(),
+					'price_micros'                     => $price_insights_result->getProductView()->getPriceMicros(),
+					'currency_code'                    => $price_insights_result->getProductView()->getCurrencyCode(),
+					'suggested_price_micros'           => $price_insights_result->getPriceInsights()->getSuggestedPriceMicros(),
+					'predicted_impressions_change_fraction' => $price_insights_result->getPriceInsights()->getPredictedImpressionsChangeFraction(),
+					'predicted_clicks_change_fraction' => $price_insights_result->getPriceInsights()->getPredictedClicksChangeFraction(),
+					'predicted_conversions_change_fraction' => $price_insights_result->getPriceInsights()->getPredictedConversionsChangeFraction(),
+					'effectiveness'                    => '', // $price_insights_result->getPriceInsights()->getEffectiveness() is not returning error, returning null.
```
Comment (mukeshpanchal27) [inline src/API/Google/MerchantPriceBenchmarks.php:116]: @joemcgill  Added note here `$price_insights_result->getPriceInsights()->getEffectiveness() is not returning error, returning null.`

Comment (joemcgill) [reply src/API/Google/MerchantPriceBenchmarks.php:116]: We'll likely need to modify the query to add an additional `price_insights.effectiveness` column, looking at [these docs](https://developers.google.com/shopping-content/reference/rest/v2.1/reports/search#priceinsights). We can handle that in #2911 .

**Review by joemcgill — APPROVED** [review]
This is working great. Thanks, @mukeshpanchal27!
