### PR TITLE
Skip orphaned variations instead of throwing errors when syncing products

### LINKED ISSUE #887: Variable Subscriptions attempting to sync
### Describe the bug:
It's a pretty rare scenario, but if we have have Variable Subscription products saved, the variations are saved with the product type set to `variation`. With the Subscription plugin active, these are skipped (seems like a filter changes the product type there), however when we deactivate the Subscription plugin and sync all products, it still picks up those variations and tries to sync them in a batch.

The batch fails with the error:
```
action failed via WP Cron: The value of parent_wc_product must be an instance of WC_Product_Variable.
```

_Note: Even though just one product in the batch fails, the whole batch is stopped and none of those products are updated._
_Note2: The batch is retried with the same product set, but fails repeatedly until the error threshold rate is reached._

With the subscription plugin active those products are not included in the batch (because the product type doesn't match). To keep the behaviour consistent should we check the parent product type in the `is_sync_ready` function since those are stored as subscription_product it will automatically skipped those and the batch can continue.

### Expected behavior:
The batches to process and skip any subscription products (including it's variations).

### Steps to reproduce:
1. Activate Subscription plugin
2. Create a variable subscription product
3. Deactivate Subscription plugin
4. Sync all products (async) in connection test
5. View the failed scheduled actions and see the error "The value of parent_wc_product must be an instance of WC_Product_Variable"

### LINKED ISSUE #888: Orphaned variation halts creating batches
### Describe the bug:
When updating all products (async), if we encounter an orphaned variation the action `gla/jobs/update_all_products/create_batch` fails (since it fails it doesn't process any followup batches for the remaining products. The error that's given is:

```
action failed via WP Cron: Invalid product ID: 0
```

One way to get around this is to go to WooCommerce > Status > Tools and use the tool to cleanup the orphaned variations. Although I think our process should be a little more robust and just skip the invalid product/variation (log the skip) and continue processing the other products.

### Expected behavior:
Updating products continues and skips invalid products/variations

### Steps to reproduce:
1. Edit one of the variations in the DB and change the `post_parent` to a non existing product like 9999999
2. Update all products (async) on the Connection test page
3. Go to WooCommerce > Status > Scheduled Actions and check the failed actions
4. See the failed action with the message `Invalid product ID: 0`

### PR DESCRIPTION
**Pull request by nima-karimi**
### Changes proposed in this Pull Request:

Closes #888.
Closes #887.

This PR adds error handling and fault tolerance to the methods and classes related to product syncing functionality so that it doesn't fail when an exception is thrown while creating and validating products.

`try ... catch` blocks are added to catch the exceptions thrown by `WC::get_product` and silently log them. In some cases (like `is_sync_ready`), a default value is returned when this exception is thrown so that the product can be skipped without disrupting the syncing process.

The `product_id` argument of `WC::get_product` and `ProductHelper::get_wc_product` is also changed to always except an `int`. These methods were never called with a `false` argument and I think it's just safer to type-hint them.

### Detailed test instructions:

1. Edit one of the variations in the DB and change the `post_parent` to a non-existing product like 9999999
1. Update all products (async) on the Connection test page
1. Go to `WooCommerce > Status > Scheduled Actions` and check the failed actions
1. The syncing should not fail
1. The orphan variation should not be synced to MC but other products are synced

Also, run `phpunit` and make sure all the tests pass.

### Changelog entry

> Fix - Skip orphaned variations instead of throwing errors when syncing products.

### CODE REVIEW

**Comment by nima-karimi** [comment]
This PR also resolves https://github.com/woocommerce/google-listings-and-ads/issues/887 since it fixes the issue with variable subscription products halting the sync process when the subscription plugin is disabled.

File: src/Product/ProductHelper.php [hunk 1]
```diff
@@ -353,36 +393,71 @@ public function get_sync_status( WC_Product $wc_product ): ?string {
...
-	 * @throws InvalidValue If a given ID doesn't reference a valid product.
+	 *
+	 * @throws InvalidValue If a given ID doesn't reference a valid product. Or if a variation product does not have a
+	 *                      valid parent ID (i.e. it's an orphan).
 	 */
-	public function maybe_swap_for_parent_id( $product ): int {
-		if ( is_integer( $product ) ) {
-			$product = $this->get_wc_product( $product );
-		}
+	public function maybe_swap_for_parent_id( int $product ): int {
```
Comment (mikkamp) [inline src/Product/ProductHelper.php]: Just for consistent naming, can we call this variable `$product_id`

**Review by mikkamp — APPROVED** [review]
Looks good, everything is working as expected and all the tests pass. I get the expected log entries for both scenarios:

```
2021-07-26T14:15:14+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductHelper::is_sync_ready Cannot sync an orphaned variation (ID: 51).

2021-07-26T14:15:35+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\BatchProductHelper::validate_and_generate_update_request_entries Skipping product (ID: 1420) due to exception: The value of parent_wc_product must be an instance of WC_Product_Variable.
```

I just left one small minor comment, but other then that it's good to go.
