### PR TITLE
Process all batches when updating products

### LINKED ISSUE #861: Product Sync batches can be empty
### Describe the bug:
When we sync a lot of products we divide it into batches (default 100) per batch. Each batch can be a mix of single products + variations. In our [original query](https://github.com/woocommerce/google-listings-and-ads/blob/1.1.0/src/Product/ProductRepository.php#L204-L217) to get the included ID's we exclude any products that are set to `dont-sync-and-show`, as well as exclude any other products which are not ready for syncing. Once we get a batch of products we run them through an [additional filter](https://github.com/woocommerce/google-listings-and-ads/blob/1.1.0/src/Product/ProductRepository.php#L175-L199) to make sure they are fully sync ready. When this filtering is done it can choose to exclude products based on additional criteria. In theory it will just make the batch size smaller, but in theory it's possible to make a batch size reduce to zero which could cause it to trigger `handle_complete` and stop processing subsequent batch jobs.

One way we can see this happening is if we have a large amount of variable products which we set to `dont-sync-and-show`. This value is only saved for the parent product. So when we query simple products and variations we will also include the variations whose parent is set to `dont-sync-and-show`. If we happen to have 4 variable products in a row with 25 variations each that can reduce a complete batch to empty and triggered it to stop processing subsequent batches.

I'm not sure whether it would warrant saving the visibility status for each variable product, or whether we would be better off detecting the total amount of batches in a different way. Not as common, but in theory it could also be reproduced with a large amount of bundled products which are not eligible.

### Steps to reproduce
It's a little hard to reproduce since we don't determine the order in which the products are synced, but here is the general steps to reproduce it:
1. It's easier to reproduce with a smaller batch size, such as:
```
add_filter(
	'woocommerce_gla_batched_job_size',
	function( $size ) {
		return 10;
	}
);
```
2. Have a large amount of variable products set to `dont-sync-and-show`
3. Since we don't determine the order the variable products would have to come before any later created products
4. When syncing all products observe the batches and notice that later batches can be missing once a larger variable product is skipped from syncing

### PR DESCRIPTION
**Pull request by mikkamp**
### Changes proposed in this Pull Request:

This PR changes the responses returned by the ProductRepository class to return an instance of ProductList. A ProductList can contain both a set of products/ids as well as the count before filtering. We use this count to confirm that we need to process additional batches of products.

Initially I was planning to use the `paginate = true` option to `wc_get_products` however in the end I decided to simplify it to only store the unfiltered count. Using the pagination option could lead to additional DB queries and resource usage.

Closes #861

### Detailed test instructions:

1. Start with trunk
2. Set some variable products to "Do not Sync and Show" (preferably ones with a lower product ID)
3. Confirm we have more products / variations then default batch size of 100, otherwise use the code snippet to decrease it:
```
add_filter(
	'woocommerce_gla_batched_job_size',
	function( $size ) {
		return 10;
	}
);
```
4. Sync all the products (async) on the Connection test page
5. Check WooCommerce > Status > Scheduled Actions and view the completed actions
6. Confirm that as soon as we encounter a batch containing less then batch size products, no new batch is scheduled
7. Checkout PR and repeat steps 2 to 5
8. Confirm that even if we encounter a batch containing less then batch size products batches are continued to be scheduled
9. Confirm unit test for unfiltered_count passes in PR

### Changelog entry
* Fix - Process all batches when updating products.

### CODE REVIEW

File: src/Product/ProductList.php [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+/**
+ * Class ProductList
+ *
+ * A list of products returned from wc_get_products.
+ *
+ * @since x.x.x
+ *
+ * @package Automattic\WooCommerce\GoogleListingsAndAds\Product
+ */
+class ProductList {
```
Comment (nima-karimi) [inline src/Product/ProductList.php]: Probably be good to have this implement `ArrayAccess` and `Countable` and/or `Traversable` or `Iterator` interfaces. Just so that we won't have to keep calling `->get`.

And I think this should be renamed to be more specific like `FilteredProductList` since we have an `unfiltered_count` here.

File: src/Product/ProductList.php [hunk 2]
```diff
@@ -0,0 +1,68 @@
+<?php
+
```
Comment (nima-karimi) [inline src/Product/ProductList.php]: `declare( strict_types=1 );` and `defined( 'ABSPATH' ) || exit;` missing here.

File: src/Jobs/AbstractBatchedActionSchedulerJob.php [hunk 3]
```diff
@@ -21,6 +21,15 @@
...
 abstract class AbstractBatchedActionSchedulerJob extends AbstractActionSchedulerJob implements BatchedActionSchedulerJobInterface {
 
+	/**
+	 * Original item count for a batch.
+	 *
+	 * @since x.x.x
+	 *
+	 * @var int|null
+	 */
+	protected $unfiltered_count;
```
Comment (nima-karimi) [inline src/Jobs/AbstractBatchedActionSchedulerJob.php]: Do we need to define this as a class property? Seems like it's only used in one method and `count()` isn't an expensive function (O(1)) so it would be fine to run it multiple times.

**Review by nima-karimi — COMMENTED** [review]
I'm wondering why you didn't create a separate utility class to handle product filtering. It seems unnecessary to modify all methods of the `ProductRepository` class to return an instance of `ProductList` since we only need it in our jobs.

I suggest we create a new `ProductFilter` class that includes the `filter_sync_ready_products` and only return a `ProductList` (or `FilteredProductList`) there. This way we would have fewer changes in the code and it would separate the filtering responsibility from `ProductRepository`.

File: src/Product/ProductList.php (hunk 1 above)
Comment (mikkamp) [reply src/Product/ProductList.php]: I considered that but didn't want to add too many functions to the class which we don't even use. It will be less relevant if we add a `ProductFilter` class since there will be less functions handling a filtered product list.

File: src/Jobs/AbstractBatchedActionSchedulerJob.php (hunk 3 above)
Comment (mikkamp) [reply src/Jobs/AbstractBatchedActionSchedulerJob.php]: The unfiltered count keeps track of the product list before it was filtered. When we reach the count we no longer know what the previous unfiltered list was.

**Comment by mikkamp** [comment]
I guess it's back to the drawing board with all the suggested changes. My initial expectancy was that a lot more functions needed to be modified in the `ProductRepository` class, but it turned out that we only filter in very few of them. I'm going to explore those suggestions.

File: src/Product/ProductList.php (hunk 1 above)
Comment (mikkamp) [reply src/Product/ProductList.php]: I played around with trying to implement the extra interfaces. But we use strict type checking, so even though we can access the results like an array we'll still need a whole other set of changes so it allows passing the list as an object, that makes the extra `->get` calls seem less intrusive.

**Comment by mikkamp** [comment]
Thanks @nima-karimi for all the suggestions. I've refactored it based on some of your suggestions. I wasn't able to fully implement ArrayAccess since we use strict type checking and that requires us to pass an array, I've only changed the functions that actually filter, so the usage of `->get` is minimized.

It's ready for another round of review.

File: src/Product/FilteredProductList.php [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+	 */
+	protected $unfiltered_count;
+
+	/**
+	 * FilteredProductList constructor.
+	 *
+	 * @param array $products         List of filtered products.
+	 * @param array $unfiltered_count Product count before filtering.
+	 */
+	public function __construct( $products, $unfiltered_count ) {
```
Comment (nima-karimi) [inline src/Product/FilteredProductList.php]: missing type hints here

File: src/Product/FilteredProductList.php [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+	 *
+	 * @var int
+	 */
+	protected $unfiltered_count;
+
+	/**
+	 * FilteredProductList constructor.
+	 *
+	 * @param array $products         List of filtered products.
+	 * @param array $unfiltered_count Product count before filtering.
```
Comment (nima-karimi) [inline src/Product/FilteredProductList.php]: tiny typo
```suggestion
	 * @param int $unfiltered_count Product count before filtering.
```

File: src/Product/FilteredProductList.php [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+	 * Count before filtering.
+	 *
+	 * @var int
+	 */
+	protected $unfiltered_count;
+
+	/**
+	 * FilteredProductList constructor.
+	 *
+	 * @param array $products         List of filtered products.
```
Comment (nima-karimi) [inline src/Product/FilteredProductList.php]: probably best to have the types here too

```suggestion
	 * @param WC_Product[]|int[] $products         List of filtered products.
```

File: src/Jobs/AbstractBatchedActionSchedulerJob.php [hunk 7]
```diff
@@ -67,15 +67,18 @@ public function handle_create_batch_action( int $batch_number ) {
 		$this->monitor->validate_failure_rate( $this );
 
 		$items = $this->get_batch( $batch_number );
+		$count = $this->unfiltered_count ?? count( $items );
```
Comment (nima-karimi) [inline src/Jobs/AbstractBatchedActionSchedulerJob.php]: I don't think it's a good idea to add `unfiltered_count` here. This class is supposed to be abstract and we're now including child class' logic into it.

What we can do instead is to override the `handle_create_batch_action` in classes that need them and, for example, instead of having a global `unfiltered_count` variable, we pass it as an argument. We might also be able to use a trait to define a common method and reuse that one.

I'm just not sure if WordPress' `add_filter` function called in the `init` method will pick up the child's `handle_create_batch_action` method instead of the parent's. But even if it doesn't we could override the `init` method in child class.

File: src/Product/FilteredProductList.php [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+/**
+ * Class FilteredProductList
+ *
+ * A list of filtered products and their total count before filtering.
+ *
+ * @since x.x.x
+ *
+ * @package Automattic\WooCommerce\GoogleListingsAndAds\Product
+ */
+class FilteredProductList implements Countable {
```
Comment (nima-karimi) [inline src/Product/FilteredProductList.php:20]: > I considered that but didn't want to add too many functions to the class which we don't even use. It will be less relevant if we add a ProductFilter class since there will be less functions handling a filtered product list.

We could also use PHP's own `ArrayIterator` here that implements all those interfaces (including `Countable`) and the necessary methods. 

The `FilteredProductList` could implement the `IteratorAggregate` interface and then return an instance of `ArrayIterator`. This way we get all the benefits without overriding those functions ourselves. 

We could get rid of the extra `->get` call and just include the custom methods like `get_unfiltered_count` and `get_product_ids`.

File: src/Product/ProductFilter.php [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+use WC_Product;
+
+/**
+ * Class ProductFilter
+ *
+ * Filters a list of products retrieved from the repository.
+ *
+ * @package Automattic\WooCommerce\GoogleListingsAndAds\Product
+ */
+class ProductFilter implements Service {
```
Comment (nima-karimi) [inline src/Product/ProductFilter.php:17]: missing `@since`

**Review by nima-karimi — COMMENTED** [review]
Thanks for all the refactoring, @mikkamp. I left a few more comments.

File: src/Jobs/AbstractBatchedActionSchedulerJob.php (hunk 7 above)
Comment (mikkamp) [reply src/Jobs/AbstractBatchedActionSchedulerJob.php]: Thanks, it makes sense to have the logic in the child class only. At the moment we only have the UpdateAllProducts job which uses it so no need to create a trait yet.

All these functions are defined in an interface so we can't just change the parameters, but I've added a separate function which gets a filtered batch.

File: src/Product/FilteredProductList.php (hunk 8 above)
Comment (mikkamp) [reply src/Product/FilteredProductList.php:20]: I'd like to get rid of the extra get calls, but regardless of which class we extend or implement we will always get an object back. When we get this object back we need to pass it's list on to functions like these:

```
AbstractBatchedActionSchedulerJob::schedule_process_action( array $items )
AbstractBatchedActionSchedulerJob::get_batch( int $batch_number ): array
ProductSyncer::update( array $products ): BatchProductResponse
```

Do you think we should remove the type restriction for those functions? Or should we have another way to pass it an array instead of an object?

Comment (nima-karimi) [reply src/Product/FilteredProductList.php:20]: Yeah, you're right. We need those type checks and it's not worth removing them just to satisfy this particular case.

We could modify the types to be a general class like `ArrayCollection` and have the `FilteredProductList` extend that but it's probably best not to make things more complicated than we need to.

Even if we don't remove the `get` calls, it might be a good idea to make this iterable because it is in fact designed for holding an array. We can cast it to `array` if we don't want to deal with type hints. Given the effects you mentioned, it's not very critical to make this change. Totally up to you.

Comment (mikkamp) [reply src/Product/FilteredProductList.php:20]: Thanks for the clarifications. My gut feeling tells me to leave it as is. While making it iterable sounds useful, we don't actually iterate through the list, we just pass it on to another function as an array before iterating.
Casting to an array is kind of the same as using a `->get` function because PHP has discussed a magic method for casting to array but it's never been implemented, so we have to rely on a custom function to get the array.

**Comment by mikkamp** [comment]
I've decided to leave it as is, see [comment](https://github.com/woocommerce/google-listings-and-ads/pull/875#discussion_r677478278)

So it's ready for another round of review.

File: src/Jobs/UpdateAllProducts.php [hunk 10]
```diff
@@ -35,9 +37,56 @@ public function get_name(): string {
 	 * @return array
 	 */
 	public function get_batch( int $batch_number ): array {
+		return $this->get_filtered_batch()->get();
```
Comment (nima-karimi) [inline src/Jobs/UpdateAllProducts.php]: Forgot to pass the `$batch_number` here.
```suggestion
		return $this->get_filtered_batch( $batch_number )->get();
```

File: src/Jobs/UpdateAllProducts.php [hunk 11]
```diff
@@ -35,9 +37,56 @@ public function get_name(): string {
...
+	/**
+	 * Get a single filtered batch of items.
+	 *
+	 * If no items are returned the job will stop.
+	 *
+	 * @param int $batch_number The batch number increments for each new batch in the job cycle.
+	 *
+	 * @return FilteredProductList
+	 */
+	protected function get_filtered_batch( int $batch_number ): FilteredProductList {
```
Comment (nima-karimi) [inline src/Jobs/UpdateAllProducts.php:54]: missing `@since` here and on another method in this class (should we add it for methods that we override?)

**Review by nima-karimi — CHANGES_REQUESTED** [review]
Still testing it but there's one place where an argument is missing.

File: src/Jobs/UpdateAllProducts.php (hunk 10 above)
Comment (mikkamp) [reply src/Jobs/UpdateAllProducts.php]: Thanks for catching that. This function is no longer actually used, but we can't remove it because the interface requires it to be implemented.

**Review by nima-karimi — APPROVED** [review]
Thanks for making all the changes. It works as intended.
