### PR TITLE
Fix/939 postcode is not always required

### LINKED ISSUE #939: Postcode is not always required
### Describe the bug:
When we edit the contact information we only allow the address to be updated if street,city,country,postcode are all populated. State can be optional for some countries so it's not included in the list. But postcode is another one which is optional for some countries. In the WooCommerce backend it does not require these store fields, but in the frontend there is some conditional logic [whether a postcode is required](https://github.com/woocommerce/woocommerce/blob/5.5.2/includes/class-wc-countries.php#L801-L804) (or is even displayed).

A quick solution might be to make postcode optional (like state is optional), but we might want to consider making it conditional based on the country in the future.

### Expected behavior:
For countries where the postcode is not a requirement we should not enforce it when trying to save contact information.

### Steps to reproduce:
1. Set the store address without a zipcode (optionally a country like Ireland that doesn't require a zipcode but it's not enforced for store address)
2. Go to edit contact information page and confirm that we are unable to save details

### PR DESCRIPTION
**Pull request by jorgemd24**
### Changes proposed in this Pull Request:

Closes #939.

### Context: 
The address validation is currently done in the frontend. It is checking if the address, city, country and postcode are filled without considering that in some countries the postcode or the state are not required. 

[`const isAddressFilled = !! ( address && city && country && postcode );`](https://github.com/woocommerce/google-listings-and-ads/blob/48df4fb68654be8c6952149aba9cfd0623ef7fba/js/src/hooks/useStoreAddress.js#L69)

If any of those values are empty it will consider that the address is incorrect. The consequences of this issue are: 

-  The user is not able to finish the onboarding process because the "complete setup" button is disabled
-  The user is not able to edit the store settings in the GLA plugin because the "save" button is disabled.

### Proposal:
In this PR I am proposing to do the validation in the backend using the method [WC_Countries::get_country_locale](https://github.com/woocommerce/woocommerce/blob/f27b4fbeba52eab06d91c3b14b2f7777f38a46f3/includes/class-wc-countries.php#L795) to get the required fields depending on the country and sending the validation to the client.

The response of `mc/contact-information` endpoint will have a  new property `has_address_errors` that will contain the required fields that are empty. If all the required fields are filled successfully, it will return an empty array.

In the future, we could expose these errors and it will help to tackle issue #634 

### Screenshots:

Example using Ireland (postcode is not required) and UK (postcode is required).

https://user-images.githubusercontent.com/2488994/147482638-ff043cc8-8a08-4b9f-8b74-caa72b3f50a9.mov

### Onboarding

1. Go to Step 4 on the initial onboarding page.
2. Confirm your phone & tick all the Pre-Launch Checklists.
3. Edit your store address in WC Settings, choose one country where is not required postcode such as Ireland, Singapur, Emirates and leave blank the postcode.
3. Click save changes.
4. Go back to the "Onboarding page" and click "Refresh to sync" and the button "Complete Setup" should be enabled.

### Edit Page

1. Go to the GLA Plugin -> Settings -> In the section "Contact Information / Edit your store" click on "Edit".
2. Edit your store address in WC Settings, choose one country where is not required postcode such as Ireland, Singapur, Emirates and leave blank the postcode.
3. Click save changes.
4. Go back to the "Edit Store Address" in the GLA page and click "Refresh to sync" and the button "Save details" should be enabled.

If you repeat steps 2 and 3 but leave the postcode empty and choose one country where the postcode is required, the button "Save Details" should be disabled.

**Keep in mind that the button will also be disabled if it detects that the Google MC and WC Store addresses are the same.**

### Changelog entry

 > Fix - MC address validation

### CODE REVIEW

File: src/API/Site/Controllers/MerchantCenter/ContactInformationController.php [hunk 1]
```diff
@@ -243,13 +248,16 @@ protected function get_contact_information_response( ?AccountBusinessInformation
 			}
 		}
 
+		$has_address_errors = $this->settings->has_address_errors( $wc_address );
```
Comment (puntope) [inline src/API/Site/Controllers/MerchantCenter/ContactInformationController.php]: 💅  WDYT of `$wc_address_errors` instead of `$has_address_errors` 

`$has_address_errors` implies that it has errors.

File: src/API/Site/Controllers/MerchantCenter/ContactInformationController.php [hunk 2]
```diff
@@ -155,6 +155,11 @@ protected function get_schema_properties(): array {
 				'description' => __( 'Whether the Merchant Center account address is different than the WooCommerce store address.', 'google-listings-and-ads' ),
 				'context'     => [ 'view' ],
 			],
+			'has_address_errors'      => [
+				'type'        => 'array',
+				'description' => __( 'Whether the Merchant Center account address has errors', 'google-listings-and-ads' ),
```
Comment (puntope) [inline src/API/Site/Controllers/MerchantCenter/ContactInformationController.php]: 💅  Related to the naming. "Whether the..." implies a boolean, when array is expected.

File: js/src/hooks/useStoreAddress.js [hunk 3]
```diff
@@ -66,7 +66,11 @@ export default function useStoreAddress( source = 'wc' ) {
 
 		const [ address, address2 = '' ] = streetAddress.split( '\n' );
 		const country = countryNameDict[ storeAddress?.country ];
-		const isAddressFilled = !! ( address && city && country && postcode );
+		const isAddressFilled =
+			Array.isArray( contact.has_address_errors ) &&
+			contact.has_address_errors.length > 0
+				? false
+				: true;
```
Comment (puntope) [inline js/src/hooks/useStoreAddress.js]: 💅  This was a bit confusing for me at first glance. 

❓  Why we need `Array.isArray( contact.has_address_errors )` as far as I read the code in Backend we are using types and we are returning always an array. So this made me thing... mmm It could be the case other type than array is returned? 

💅  

`const isAddressFilled = contact.has_address_errors.length > 0 ? false : true;`

I'd change this to... 

`const isAddressFilled = ! contact.wc_address_errors.length;`

See also my comment [here](https://github.com/woocommerce/google-listings-and-ads/pull/1169/files#r778182747) regarding  the `has_address_errors` name.

File: src/API/Google/Settings.php [hunk 4]
```diff
@@ -387,6 +387,58 @@ public function get_store_address(): AccountAddress {
...
+	/**
+	 * Check whether the address has errors
+	 *
+	 * @param AccountAddress $address to be validated.
+	 *
+	 * @return array
+	 */
+	public function has_address_errors( AccountAddress $address ): array {
+		if ( ! $address instanceof AccountAddress ) {
+			return [];
```
Comment (puntope) [inline src/API/Google/Settings.php]: ❓  So if we send something wrong to `has_address_errors` is returns [], hence no error?

File: src/API/Google/Settings.php [hunk 5]
```diff
@@ -387,6 +387,58 @@ public function get_store_address(): AccountAddress {
...
+		}
+
+		/** @var WC $wc */
+		$wc = $this->container->get( WC::class );
+
+		$country   = $address->getCountry();
+		$countries = $wc->get_wc_countries();
+
+		$locale          = $countries->get_country_locale();
+		$locale_settings = isset( $locale[ $country ] ) ? $locale[ $country ] : [];
```
Comment (puntope) [inline src/API/Google/Settings.php]: 💅  WDYT of `$locale[ $address->getCountry() ] ?? []` 

Info --> https://www.php.net/manual/en/migration70.new-features.php#:~:text=Null%20coalescing%20operator%20%C2%B6

File: src/API/Google/Settings.php [hunk 6]
```diff
@@ -387,6 +387,58 @@ public function get_store_address(): AccountAddress {
...
+	}
+
+	/**
+	 * Check whether the required address fields are empty
+	 *
+	 * @param array $address_fields to be validated.
+	 * @param array $locale_settings locale settings
+	 * @return array
+	 */
+	public function validate_address( array $address_fields, array $locale_settings ) {
```
Comment (puntope) [inline src/API/Google/Settings.php]: 💅  return type missed

File: src/API/Google/Settings.php (hunk 4 above)
Comment (puntope) [reply src/API/Google/Settings.php]: Also this condition is always 'false' because 'AccountAddress $address' is evaluated at this point because of the types

File: src/API/Google/Settings.php [hunk 7]
```diff
@@ -387,6 +387,58 @@ public function get_store_address(): AccountAddress {
...
+		$errors = array_filter(
+			$address_fields,
+			function ( $field ) use ( $locale_settings, $address_fields ) {
+				$is_required = isset( $locale_settings[ $field ] ) && isset( $locale_settings[ $field ]['required'] ) ? $locale_settings[ $field ]['required'] : true;
+				return true === $is_required && empty( $address_fields[ $field ] ) ? true : false;
```
Comment (puntope) [inline src/API/Google/Settings.php]: 💅  WDYT of this

```
$is_required = $locale_settings[ $field ]['required'] ?? true;
return $is_required && empty( $address_fields[ $field ] );
```

File: src/API/Site/Controllers/MerchantCenter/ContactInformationController.php [hunk 8]
```diff
@@ -243,13 +248,16 @@ protected function get_contact_information_response( ?AccountBusinessInformation
...
+		$has_address_errors = $this->settings->has_address_errors( $wc_address );
+
 		return $this->prepare_item_for_response(
 			[
 				'id'                      => $this->options->get_merchant_id(),
 				'phone_number'            => $phone_number,
 				'mc_address'              => self::serialize_address( $mc_address ),
 				'wc_address'              => self::serialize_address( $wc_address ),
 				'is_mc_address_different' => $is_address_diff,
+				'has_address_errors'      => $has_address_errors,
```
Comment (puntope) [inline src/API/Site/Controllers/MerchantCenter/ContactInformationController.php]: 💅  See naming suggestions

File: tests/Unit/MerchantCenter/ValidateAddressTest.php [hunk 9]
```diff
@@ -0,0 +1,124 @@
+<?php
```
Comment (puntope) [inline tests/Unit/MerchantCenter/ValidateAddressTest.php:1]: 🥳  Nice thanks for adding tests

**Review by puntope — COMMENTED** [review]
Overall LGTM, thanks for fixing this ✅  

- Added Spain with no postcode and wen to to  GLA Address Settings, The system didn't allow me to Save.✅ 
- Went back to WC settings and added Postcode. GLA Address Settings allowed me to save.✅ 
- Went back to WC settings and removed Postcode, selected Ireland.  GLA Address Settings allowed me to save. ✅ 

💅 / ❓   Some questions/opinions regarding some naming and checks structures. 
🧪  Thanks for adding test in the backend, however test is missing in the frontend.

File: src/API/Google/Settings.php (hunk 4 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php]: Yes, you are right it is unnecessary as PHP will throw an error before evaluating that condition. 

Has been removed in [7b1c89b](https://github.com/woocommerce/google-listings-and-ads/pull/1169/commits/7b1c89bf566dfd9c097f84ac6e9d256a54f7b584)

File: js/src/hooks/useStoreAddress.js (hunk 3 above)
Comment (jorgemd24) [reply js/src/hooks/useStoreAddress.js]: I think I went too cautious here doing that double checking with the array. See commit: [7b1c89b](https://github.com/woocommerce/google-listings-and-ads/pull/1169/commits/7b1c89bf566dfd9c097f84ac6e9d256a54f7b584)

File: src/API/Google/Settings.php (hunk 6 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php]: ✅   [#7b1c89b](https://github.com/woocommerce/google-listings-and-ads/pull/1169/commits/7b1c89bf566dfd9c097f84ac6e9d256a54f7b584)

File: src/API/Google/Settings.php (hunk 7 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php]: Nice one! See : [#1129695](https://github.com/woocommerce/google-listings-and-ads/pull/1169/commits/1129695a2755c977b462f9f2f50249642017655f)

File: src/API/Google/Settings.php (hunk 5 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php]: I think both versions are given the same result in this context. In this case, I think the ternary operator would give better readability but is adding more verbosity to the code.

Just to keep the same consistency with the other changes I have updated the null coalescing operator. See [#7b1c89b](https://github.com/woocommerce/google-listings-and-ads/pull/1169/commits/7b1c89bf566dfd9c097f84ac6e9d256a54f7b584)

File: src/API/Site/Controllers/MerchantCenter/ContactInformationController.php (hunk 1 above)
Comment (jorgemd24) [reply src/API/Site/Controllers/MerchantCenter/ContactInformationController.php]: I think  $gla_address_errors or $mc_address_errors instead of $wc_address_errors would be better as the issue is more related to Google Merchant Center/ GLA plugin than with WC. WC is not really doing that validation. WDYT?

Comment (puntope) [reply src/API/Site/Controllers/MerchantCenter/ContactInformationController.php]: That would work as well! 👌  My main concern was the prefix 'has' or 'is' which implies a boolean condition.

**Review by puntope — APPROVED** [review]
Thanks for the changes @jorgemd24! 

If you finally change the name of `has_address_errors`  and want a new check let me know, otherwise I guess this could be merged directly.

File: src/API/Google/Settings.php [hunk 10]
```diff
@@ -387,6 +387,53 @@ public function get_store_address(): AccountAddress {
...
+	 *
+	 * @param array $address_fields to be validated.
+	 * @param array $locale_settings locale settings
+	 * @return array
+	 */
+	public function validate_address( array $address_fields, array $locale_settings ): array {
+		$errors = array_filter(
+			$address_fields,
+			function ( $field ) use ( $locale_settings, $address_fields ) {
+				$is_required = $locale_settings[ $field ]['required'] ?? true;
```
Comment (eason9487) [inline src/API/Google/Settings.php:428]: I think the default `is_required` should be `false`? Otherwise, countries like Singapore, [which do not have specified postcode filed in locale settings](https://github.com/woocommerce/woocommerce/blob/6.0.0/plugins/woocommerce/includes/class-wc-countries.php#L1310-L1318), the postcode may not be required, but the default `true` would cause it to still block the submit button if users have not filled in postcode.

File: src/API/Google/Settings.php [hunk 11]
```diff
@@ -387,6 +387,53 @@ public function get_store_address(): AccountAddress {
...
+				return $is_required && empty( $address_fields[ $field ] );
+			},
+			ARRAY_FILTER_USE_KEY
+		);
+
+		return array_keys( $errors );
+	}
```
Comment (eason9487) [inline src/API/Google/Settings.php:435]: [The default **state** of locale settings is required](https://github.com/woocommerce/woocommerce/blob/6.0.0/plugins/woocommerce/includes/class-wc-countries.php#L738-L746), but this does not seem to be correct for all countries. Countries like Lithuania (LT) or Taiwan (TW), which have no **state** in WC Settings and also have no specified locale settings, are impossible to proceed with submission. Because the state is always `NULL`.

image

Probably the problem belongs to WC core, but it might need to add some additional processing in GLA in advance.

**Review by eason9487 — COMMENTED** [review]
While working on other development, I found the GLA store address could not be saved with the [current `develop` branch](https://github.com/woocommerce/google-listings-and-ads/tree/daa277c2c3de6743086841ad4ab7988872f2f9d9).

File: src/API/Google/Settings.php (hunk 11 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php:435]: As we can not rely on the WC core to check if the state is required or not because WC itself is not setting this field.
I propose to remove the **state** validation so countries like Lithuania or Taiwan would not have this issue. Let me know what you think about this.

File: src/API/Google/Settings.php (hunk 10 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php:428]: If the default is `false`, the postcode would not be required for countries like [UK](https://github.com/woocommerce/woocommerce/blob/4cf10ad2174de8bde62fa1b753691e2f091db413/plugins/woocommerce/includes/class-wc-countries.php#L1416), [ES](https://github.com/woocommerce/woocommerce/blob/4cf10ad2174de8bde62fa1b753691e2f091db413/plugins/woocommerce/includes/class-wc-countries.php#L1343), [FR](https://github.com/woocommerce/woocommerce/blob/4cf10ad2174de8bde62fa1b753691e2f091db413/plugins/woocommerce/includes/class-wc-countries.php#L996) etc and that would be incorrect.

Singapore seems to use postcodes, see: https://en.wikipedia.org/wiki/Postal_codes_in_Singapore

[In the original implementation](https://github.com/woocommerce/google-listings-and-ads/blob/48df4fb68654be8c6952149aba9cfd0623ef7fba/js/src/hooks/useStoreAddress.js#L69), the postcode was always required in contrast using the class WC_Countries we are able to allow countries like Ireland, United Arab Emirates, Uganda etc be able to save the WC store without using the postcode.

Anyway, I think it is a good idea to show the errors as was mentioned in #634 so the users know the reason why the button is disabled.

Comment (eason9487) [reply src/API/Google/Settings.php:428]: > 3. Edit your store address in WC Settings, choose one country where is not required postcode such as Ireland, Singapur, Emirates and leave blank the postcode.

I followed the test instructions to set Singapore as WC store address, and then I could not finish the onboarding setup. So I thought it was a problem. 😅 

> Singapore seems to use postcodes, see: https://en.wikipedia.org/wiki/Postal_codes_in_Singapore

Seems like the `required` postcode of locale settings in WC core is not quite correct to be treated as a must-required field. In Taiwan, we do have postcodes but it's not required address info for most cases, a postcode is still recommended to be filled when providing address though.

I think it's probably a trade-off when choosing to make it required or not if a country is not really required a postcode to identify an address. Just mainly depends on the services to be provided, which way is preferred.  

Consider the WC Settings page would have the postcode input field when the `required` is `true` or `NULL`, so it would not totally block users to finish the onboarding setup. It should be ok to keep it as is.

File: src/API/Google/Settings.php (hunk 11 above)
Comment (eason9487) [reply src/API/Google/Settings.php:435]: > I propose to remove the **state** validation so countries like Lithuania or Taiwan would not have this issue. Let me know what you think about this.

I think it will work well. If a country has states, the state will be selected together when choosing a country in WC Settings. So it should be ok to skip the check of **state**.

image

File: src/API/Google/Settings.php (hunk 10 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php:428]: Using WC_Countries allow us to be more flexible with the postcode requirement, with the previous implementation the postcode was always required and even countries that have the postcode requirement = `false` in WC could not complete the onboarding process.

File: src/API/Google/Settings.php (hunk 11 above)
Comment (jorgemd24) [reply src/API/Google/Settings.php:435]: I will create a small PR removing the state validation and I will keep the validation of the rest of the fields. Let me know if you agree with this so I can proceed. Thanks @eason9487!

File: src/API/Google/Settings.php (hunk 10 above)
Comment (eason9487) [reply src/API/Google/Settings.php:428]: Yes. So it should be ok to keep using `true` as default. This thread should be no longer a concern. Thanks for the finding and elaborations! 😄

File: src/API/Google/Settings.php (hunk 11 above)
Comment (eason9487) [reply src/API/Google/Settings.php:435]: Sounds great! Thank you @jorgemd24!
