### PR TITLE
Google Product Feed incompatibility account-level issue

### LINKED ISSUE #774: Incompatibility notice with Google Product Feed extension
We need to display a notice to the user if they have the [Google Product Feed](https://woocommerce.com/products/google-product-feed/) extension activated on their website. Google suggests that only one method (either API or Data Feed) be used to submit products to the Merchant Center and using both methods might lead to unexpected results. We could display a notice when a conflict is detected and add this to our docs.

https://developers.google.com/shopping-content/guides/best-practices#do-not-use-api-and-feeds
image

### PR DESCRIPTION
**Pull request by layoutd**
### Changes proposed in this Pull Request:

Closes #774.

This PR adds an account-level issue to the "Issues to resolve" list when the [Google Product Feed](https://woocommerce.com/products/google-product-feed/) plugin is detected.
- The filter `woocommerce_gla_custom_merchant_issues` is added, allowing custom issues (both account and product) to be added to the merchant issues table.
- In the `GoogleProductFeedValidator`, if the plugin is detected, then instead of showing a notice and preventing GLA from loading, the new filter is used to add an account-level issue.
- If the plugin is detected, then the `deactivated_plugin` hook is used to delete the `MC_STATUSES` cache when the plugin is deactivated, to prevent a stale issue from displaying.
    - This is done using `woogle_get_container` as the validation is performed before any services are registered (so `Transient`/`TransientInterface`/`MerchantStatus` aren't available yet).

#### Notes
- _Should_ GLA be prevented from loading (or a more visible notice be added to /wp-admin/)? In this case, a user won't see the incompatibility notice until they've already set up their Merchant Center account (which could mean they've already made a mess of their feed).
- There's a small change to the stale merchant issues removal process - now all issues that aren't explicitly updated/added during generation, are deleted. This prevents stale issues that are younger than the `STATUS_LIFETIME`, but are actually no longer valid, from persisting in the table. (An example is this Google Product Feed issue: when the plugin is deactivated, the status transient is cleared, but the issues table isn't truncated. When the cache is regenerated, all issues are update-or-inserted, and issues older than 1 hour are removed. But if the plugin was deactivated less than 60 minutes ago, it's no longer valid *AND* still younger than one hour, so it persists, incorrectly).

### Screenshots:
image

### Detailed test instructions:
1. Go through Merchant Center onboarding.
2. In the Product Feed page, check that "Issues to resolve" is populated.
3. Activate the Google Product Feed plugin.
4. Clear the merchant status cache (from Connection Test).
5. Reload or revisit the Product Feed page.
    - Check that the incompatibility notice is visible in the "Issues to resolve".
6. Disable the Google Product Feed plugin, 
    - *Don't* clear the merchant status cache - it should be done automatically on deactivation.
    - Check the cache transient no longer exists:
    ``SELECT *  FROM `wp_options` WHERE `option_name` LIKE '%gla_mc_statuses'``
5. Reload or revisit the Product Feed page.
    - Check that the incompatibility notice is **NOT** visible in the "Issues to resolve".

### Changelog entry

> Add - Incompatibility warning for Google Product Feed plugin.

### CODE REVIEW

File: src/Internal/Requirements/GoogleProductFeedValidator.php [hunk 1]
```diff
@@ -0,0 +1,100 @@
+<?php
+declare( strict_types=1 );
+
+namespace Automattic\WooCommerce\GoogleListingsAndAds\Internal\Requirements;
+
+use Automattic\WooCommerce\GoogleListingsAndAds\Exception\ExtensionRequirementException;
+use Automattic\WooCommerce\GoogleListingsAndAds\MerchantCenter\MerchantStatuses;
+use Automattic\WooCommerce\GoogleListingsAndAds\Options\TransientsInterface;
```
Comment (mikkamp) [inline src/Internal/Requirements/GoogleProductFeedValidator.php]: This interface is no longer used.

File: src/Internal/Requirements/GoogleProductFeedValidator.php [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+				},
+				10,
+				2
+			);
+
+			add_filter(
+				'deactivated_plugin',
+				function( $plugin ) {
+					if ( 'woocommerce-product-feeds/woocommerce-gpf.php' === $plugin ) {
+						woogle_get_container()->get( MerchantStatuses::class )->clear_cache();
```
Comment (mikkamp) [inline src/Internal/Requirements/GoogleProductFeedValidator.php]: This feels odd, but I suppose it's the way to do it since as you mentioned, the container dependencies aren't loaded yet when we do these validation checks.

Do we need any additional validation that our plugin is indeed active and the classes are usable? I know we run this validation check as last, but in theory if we would run it in a different order (or add another validation class later on), we would hook into `deactivated_plugin` and return true. So any followup validations could prevent the services from loading.

File: src/Internal/Requirements/GoogleProductFeedValidator.php [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+			add_filter(
+				'woocommerce_gla_account_issues',
+				function( $issues, $current_time ) {
+					return $this->add_conflict_issue( $issues, $current_time );
+				},
+				10,
+				2
+			);
+
+			add_filter(
```
Comment (mikkamp) [inline src/Internal/Requirements/GoogleProductFeedValidator.php]: Is this really a filter or an action? If it would be a filter we need to remember to return a value from the function.

File: src/Internal/Requirements/GoogleProductFeedValidator.php [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+		foreach ( $issues as &$issue ) {
+			// Make sure all issues have the source attribute to avoid errors.
+			if ( ! empty( $issue['source'] ) ) {
+				continue;
+			}
+			$issue['source'] = 'mc';
+		}
+
+		$issues[] = [
+			'product_id' => '0',
```
Comment (mikkamp) [inline src/Internal/Requirements/GoogleProductFeedValidator.php]: For account issues we set this as `0` (integer). Do we need it to be a string for a particular reason here?

File: src/Internal/Requirements/GoogleProductFeedValidator.php [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+			'product'    => 'All products',
+			'code'       => 'incompatible_google_product_feed',
+			'issue'      => 'The Google Product Feed plugin may cause conflicts or unexpected results.',
+			'action'     => 'Delete or deactivate the Google Product Feed plugin from your store',
```
Comment (mikkamp) [inline src/Internal/Requirements/GoogleProductFeedValidator.php]: Can we make these string translatable?
Also I think it's better to recommend to deactivate (and then optionally delete), which gives the plugin the chance to run any cleanup functions.

File: src/MerchantCenter/MerchantStatuses.php [hunk 6]
```diff
@@ -372,6 +370,13 @@ protected function refresh_account_issues(): void {
 			];
 		}
 
+		/**
+		 * Account-level issues can be added the merchant issues table.
```
Comment (mikkamp) [inline src/MerchantCenter/MerchantStatuses.php]: Missing `to`, or maybe it needs to be reworded to state that we can use this filter to add custom account issues which will be added to the table.
Is the same hook handy for product issues? Or will we add this when we need it?

File: src/MerchantCenter/MerchantStatuses.php [hunk 7]
```diff
@@ -189,9 +189,7 @@ public function maybe_refresh_status_data( bool $force_refresh = false ): void {
 		$this->refresh_presync_product_issues();
 
 		// Delete stale issues.
-		$delete_before = clone $this->current_time;
-		$delete_before->modify( '-' . $this->get_status_lifetime() . ' seconds' );
-		$this->container->get( MerchantIssueTable::class )->delete_stale( $delete_before );
+		$this->container->get( MerchantIssueTable::class )->delete_stale( $this->current_time );
```
Comment (mikkamp) [inline src/MerchantCenter/MerchantStatuses.php]: This change works because we aren't really passing the current time but the time when the class was initialized (before we refresh account/product issues). It makes the name of the variable a bit confusing, because if we would actually be passing the current time to the delete stale function then it could be deleting more then it should.

**Review by mikkamp — COMMENTED** [review]
The changes make sense and work as intended, but I added some thoughts to take a look at.

You already mentioned it in your note, but this change is definitely geared towards getting users to switch to our plugin. If they decide to deactivate our plugin and leave GPF active then we won't undo any of the settings or product syncs.

File: src/Internal/Requirements/GoogleProductFeedValidator.php (hunk 3 above)
Comment (layoutd) [reply src/Internal/Requirements/GoogleProductFeedValidator.php]: Good catch, [definitely an action](https://developer.wordpress.org/reference/hooks/deactivated_plugin/) d953023720e1c7481095801c02aebebf15ba5e23

File: src/Internal/Requirements/GoogleProductFeedValidator.php (hunk 2 above)
Comment (layoutd) [reply src/Internal/Requirements/GoogleProductFeedValidator.php]: The other option was to simply use `delete_transient` with a hard-coded name (using `PluginHelper::get_slug()`), but this seemed  a bit more elegant.

I've added a quick check to make sure that that the container `get()` call returns the desired class before clearing the cache. If subsequent validations block the services from being registered, this should prevent a `clear_cache` call using a null variable. b4be28a113807811d069a0af19ee76f052c21921

File: src/Internal/Requirements/GoogleProductFeedValidator.php (hunk 4 above)
Comment (layoutd) [reply src/Internal/Requirements/GoogleProductFeedValidator.php]: Multi-cursor copy-pasta, fixed in d953023720e1c7481095801c02aebebf15ba5e23

File: src/Internal/Requirements/GoogleProductFeedValidator.php (hunk 5 above)
Comment (layoutd) [reply src/Internal/Requirements/GoogleProductFeedValidator.php]: That's a good point, I changed it to just `Deactivate` and will leave it up to the user whether they want to remove the deactivated plugin or not d953023720e1c7481095801c02aebebf15ba5e23

File: src/MerchantCenter/MerchantStatuses.php (hunk 7 above)
Comment (layoutd) [reply src/MerchantCenter/MerchantStatuses.php]: Clarified the variable name in 176337c91107d169e435f6cb658e1b5e264f15f4

**Comment by layoutd** [comment]
Thanks @mikkamp, I made some changes based on your comments.

**Review by mikkamp — APPROVED** [review]
Thanks for the additional refactors. I'm getting the error show up in the table, and as soon as I deactivate the plugin the cache is cleared and I get a fresh list without the error.
