### PR TITLE
Show leaving prompt in Edit Ads Campaign if the form was modified.

### LINKED ISSUE #2090: [Paid Campaigns] - Leaving the page doesn't show alert prompt after editing changes
### Describe the bug:

Related to https://github.com/woocommerce/google-listings-and-ads/issues/1640

In Free Listings, when we change the options and we attempt to leave the page, a prompt appears alerting the user about the changes not being saved. However, in Paid Ads Campaigns this is not working.

https://github.com/woocommerce/google-listings-and-ads/assets/5908855/79669366-e55e-41a7-b1e1-c15b9ba5fb80

### Steps to reproduce:

1. Go to Edit Paid Campaign
2. Change something, for example the DAILY AVERAGE COST input
3. Click on the back button on the top left
4. NO Prompt is shown

### Expected behavior:
A prompt is shown as we do in Free Listings

### Actual behavior:
A prompt is NOT shown.

### Additional details:

Several PRs and rounds of mods were happening in regard this issue:

https://github.com/woocommerce/google-listings-and-ads/pull/1670
https://github.com/woocommerce/google-listings-and-ads/pull/2077
https://github.com/woocommerce/google-listings-and-ads/pull/1580

### PR DESCRIPTION
**Pull request by puntope**
### Changes proposed in this Pull Request:

Closes #2090  .

This PR integrates the same logic as Edit Free Campaigns. To show a prompt when the user try to leave the page with changes in the form. 

Please check the issue #2090 for full context.

### Screenshots:

https://github.com/user-attachments/assets/3754f8e6-c6a4-405b-80b2-19f3a51940d3

### Detailed test instructions:

1. Enter in Edit Paid Campaign Page

-- You can leave when there are no changes -- 
3. Dont modify any data and confirm you can leave using WC Navigator in the header. 
4. Dont modify any data and confirm you can leave using browser back arrow. 
5. Dont modify any data and confirm you can leave using some link in the WordPress Menu.
6. Change something, try to go back. Verify the prompt shows. Then restore the change to what it was before. Confirm now you can leave without prompt.
7. You can navigate between steps 
8. You can save the form

-- Prompt shows when something changes -- 
9. Modify Daily average cost amount in the first step. 
10. Verify the prompt shows when you leave after change using steps 3,4 or 5.
11. Verify you can continue to next step without prompt.
12. Verify you can navigate between steps
13. You can save the form when something changes.
14. Enter again in edit paid campaign and change only values in the Assets step.
15. Verify steps 10-12 again with all the fields in assets.

### Changelog entry

> Fix - Show leaving prompt in Edit Ads Campaign if the form was modified.

### CODE REVIEW

File: js/src/pages/edit-paid-ads-campaign/index.js [hunk 1]
```diff
@@ -48,6 +51,15 @@ function getCurrentStep() {
 	return STEP.CAMPAIGN;
 }
 
+function isNotOurStep( location ) {
+	const allowList = new Set( [
+		getNewPath( { step: STEP.CAMPAIGN } ),
+		getNewPath( { step: STEP.ASSET_GROUP } ),
+	] );
+	const destination = location.pathname + location.search;
+	return ! allowList.has( destination );
```
Comment (eason9487) [inline js/src/pages/edit-paid-ads-campaign/index.js:60]: Since the different orders of `location.search` are still equivalent and this comparison process doesn't guarantee order when forming `location.search` strings, this determination might not be reliable enough across all JS engines.

Although I haven't encountered related issues when testing, I would recommend considering a more stable comparison method.

**Review by eason9487 — APPROVED** [review]
Thanks for the work.

The suggestion in the only comment is optional. Let me know if there are any further relevant changes that might need another look.

File: js/src/pages/edit-paid-ads-campaign/index.js (hunk 1 above)
Comment (puntope) [reply js/src/pages/edit-paid-ads-campaign/index.js:60]: Thanks @eason9487 Afraid my knowledge in JS is not wide enough to find more stable methods. But I will investigate further and I will try to make it to happen in follow up PRs. 

Feel free to suggest what do you think would be the best approach!
