### PR TITLE
#611: Throw an exception when invalid top level domain is returned.

### LINKED ISSUE #611: `[websiteUrl]` in MCA connection error is not resolved
### Describe the bug:
When I tried to connect to MCaccount from the local environment and domain `gla1.test`, the creation of MCA failed with an error that has `[websiteUrl]` placeholder, which I believe could be resolved to the actual URL given.

### Expected behavior:
```
Error creating account: <code>https://gla1.test/</code> URL ends with an invalid top-level domain name
```
### Actual behavior:
```
Error creating account: [websiteUrl] URL ends with an invalid top-level domain name
```
Screenshoot of the above error

### Steps to reproduce:

0. [Disconnect](https://gla1.test/wp-admin/admin.php?page=connection-test-admin-page) your MC account
1. Go to Setup MC page on you **local** domain [`gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc`](https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc)
2. Click "Create Account"
3. Wait for error

### Additional details:
I found the issue during the review of https://github.com/woocommerce/google-listings-and-ads/pull/610

### PR DESCRIPTION
**Pull request by rawdreeg**
### Changes proposed in this Pull Request:

An exception error was returned when creating a new merchant account from a site with a URL ending with an invalid top-level domain name. However, this error returned the placeholder "[websiteUrl]" instead of the invalid site URL. This PR corrects this by: 

* Catching errors related to invalid top-level domains specifically, and throwing an error that includes the site's URL.

Closes #611.

### Screenshots:
Screenshot

### Detailed test instructions:

1. [Disconnect](https://wpsandbox.localhost/wp-admin/admin.php?page=connection-test-admin-page) your MC account
2. Go to Setup MC page on you local domain [https://wpsandbox.localhost/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc](https://wpsandbox.localhost/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsetup-mc)
3. Click "Create Account"
4. The error message should include the website URL. eg Error creating an account: "https://wpsandbox.localhost" URL ends with an invalid top-level domain name

### Additional details:

> Add -A new exception class -- InvalidDomainName -- that is thrown when a Merchant Center account can't be created because of an invalid top-level domain name.
> Fix -Return an InvalidDomainName when an error related to an invalid top-level domain name is caught

### Changelog entry

> Tweak - Catch errors related to invalid top-level domains specifically, and throw an error when the site's URL ends with an invalid top-level domain.

### CODE REVIEW

File: src/API/Google/Proxy.php [hunk 1]
```diff
@@ -173,6 +175,10 @@ protected function create_merchant_account_request( string $name, string $site_u
 				throw InvalidTerm::contains_invalid_terms( $name );
 			}
 
+			if ( preg_match( '/URL?.* invalid top-level domain name/', $message ) ) {
```
Comment (mikkamp) [inline src/API/Google/Proxy.php]: Is there a specific reason we need to use a regexp like this? The `?` would imply that the `L` is optional, and if you would have intended the whole word URL to be optional then it would have also matched that with `.*`. I think in this case though it's better to use a strpos to see if it contains the string 'URL ends with an invalid top-level domain name'. The WCS already matches this exact string to allow the error to pass.

File: src/API/Google/Proxy.php [hunk 2]
```diff
@@ -173,6 +175,10 @@ protected function create_merchant_account_request( string $name, string $site_u
...
+				throw InvalidDomainName::invalid_top_level_domain_name( $this->get_site_url() );
```
Comment (mikkamp) [inline src/API/Google/Proxy.php]: Would it look a bit cleaner to pass the URL through `strip_url_protocol`, it's what we used in other places where we expose the domain name in the UI?

File: src/Exception/InvalidDomainName.php [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+	 * @param string $domain_name The top level domain name.
+	 *
+	 * @return static
+	 */
+	public static function invalid_top_level_domain_name( string $domain_name ): InvalidDomainName {
+		return new static(
+		/* translators: 1 top level domain name. */
+			sprintf( __( 'Error creating account: "%1$s" URL ends with an invalid top-level domain name.', 'google-listings-and-ads' ), $domain_name )
+		);
+	}
```
Comment (mikkamp) [inline src/Exception/InvalidDomainName.php]: Most of the Invalid... classes have very generic errors which can be reused in many places. However this error message directly specifies it occurs when the Merchant Account can't be connected, although the name of the function implies it can be used whenever an invalid top level domain is encountered. I'd suggest to rename the function to be less generic if we aren't going to reuse it.
Also in most locations in the code if we return a specific error we format it as a sentence. The prefix "Error creating account:" is only used when we don't know what the followup error will be. Maybe something like "Unable to create an account, the domain name "%s" must use a valid top level domain."

File: src/API/Google/Proxy.php [hunk 4]
```diff
@@ -137,6 +138,7 @@ public function create_merchant_account(): int {
 	 *
 	 * @throws Exception   When an Exception is caught or we receive an invalid response.
 	 * @throws InvalidTerm When the account name contains invalid terms.
+	 * @throws InvalidDomainName When an Exception related to an invalid top level domain is received.
```
Comment (mikkamp) [inline src/API/Google/Proxy.php]: Would it be clearer if we just stated "When the site URL contains an invalid top level domain"?

**Review by mikkamp — COMMENTED** [review]
Thanks for these changes, they are working and I'm getting the error with the URL as expected.

Looks like the changelog entry didn't get added as intended. Generally we'd add one line per PR, the PR itself can contain all the specifics of what was changed. I also left some additional comments on some things we could consider improving.

File: src/API/Google/Proxy.php (hunk 1 above)
Comment (rawdreeg) [reply src/API/Google/Proxy.php]: Hey @mikkamp,

I wanted to make the word (URL) optional. I went with your suggestion by simply using **strpos**. Thanks

File: src/API/Google/Proxy.php (hunk 2 above)
Comment (rawdreeg) [reply src/API/Google/Proxy.php]: Thanks for the suggestion. I have implemented it, and I will be sure to keep this in mind in the future.

File: src/Exception/InvalidDomainName.php (hunk 3 above)
Comment (rawdreeg) [reply src/Exception/InvalidDomainName.php]: > Most of the Invalid... classes have very generic errors which can be reused in many places. However this error message directly specifies it occurs when the Merchant Account can't be connected, although the name of the function implies it can be used whenever an invalid top level domain is encountered. I'd suggest to rename the function to be less generic if we aren't going to reuse it.

Thanks. Very valid point. I thought about the function name as well, and I couldn't come up with a descriptive and concise name. I now went with **create_account_failed_invalid_top_level_domain_name**

To your other point about the error sentence, I also agree. I have updated the error message with "Unable to create an account, the domain name "%s" must end with a valid top-level domain name."

File: src/API/Google/Proxy.php (hunk 4 above)
Comment (rawdreeg) [reply src/API/Google/Proxy.php]: I agree. I changed this to "When the site URL ends with an invalid top-level domain".

**Comment by rawdreeg** [comment]
> Thanks for these changes, they are working and I'm getting the error with the URL as expected.
> 
> Looks like the changelog entry didn't get added as intended. Generally we'd add one line per PR, the PR itself can contain all the specifics of what was changed. I also left some additional comments on some things we could consider improving.

Oh yes, I will add in the change log entry. Thanks

**Review by mikkamp — APPROVED** [review]
Thanks for the changes, it's returning the error as expected. I'm seeing:

> Unable to create an account, the domain name "google.test" must end with a valid top-level domain name.

For the changelog entry we usually add a prefix, in this case "Tweak" would probably be most applicable. This is because they get parsed from the PR when we release, so you can have a look at what they looked like for other PR's in the [changelog.txt](https://github.com/woocommerce/google-listings-and-ads/blob/develop/changelog.txt)

**Comment by rawdreeg** [comment]
> 

I have added the prefix. Thanks for all the help @mikkamp
