### PR TITLE
Fix useNavigateAwayPromptEffect for WC Compat with WC 6.7

### LINKED ISSUE #1579: WC 6.7 compatibility issue: navigation does not work in certain pages
### Describe the bug:

This issue arises from my WooCommerce 6.7 compatibility testing in issue https://github.com/woocommerce/google-listings-and-ads/issues/1577.

In certain pages such as Edit Free Listings, clicking on the "<" back navigation button in the plugin does not do anything. Same with clicking on the browser's back button. Clicking on the "Continue" button in the Edit Free Listings Step 1 does not bring the user to Step 2.

In addition, clicking on some other WC menu items below does not do anything too:

- WooCommerce
- WooCommerce > Home
- WooCommerce > Customers
- Analytics
- Analytics > All menu items.

This might be related: the above URLs share the same URL pattern: `/wp-admin/admin.php?page=wc-admin&path=<...>`. 

Note that this issue only happens in WC 6.7.0 beta 1 and beta 2. If we roll back to version 6.6, it works as expected. WC version switching is done by using [WooCommerce Beta Tester](https://wordpress.org/plugins/woocommerce-beta-tester/). I tested this with https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.13.6.

📹 See demo video below with my voice annotation:

https://user-images.githubusercontent.com/417342/176746047-e89ccafe-3e82-49bc-b0a8-edcb7ad75b5a.mov

### Steps to reproduce:

1. Use WC 6.7 beta 1 or beta 2.
2. Go to Edit Free Listings page. 
3. Click on the back button on the top left corner. Nothing happens.
4. Click on WooCommerce or Analytics pages. Nothing happens.

### Expected behavior:

There should be page navigation when we click on the button or menu items.

### Actual behavior:

Nothing happens when we click on the button or menu items.

### PR DESCRIPTION
**Pull request by puntope**
### Changes proposed in this Pull Request:

Closes #1579.

This PR potentially fixes incompatibility issues with WC 6.7

Seems like the new version uses a new version of history API? In any case, the method `useNavigateAwayPromptEffect` breaks the navigation in WC 6.7 

### Screenshots:

Before

https://user-images.githubusercontent.com/417342/176746047-e89ccafe-3e82-49bc-b0a8-edcb7ad75b5a.mov

After

https://user-images.githubusercontent.com/5908855/176930639-bda17e39-8a67-4298-982a-d81d540ab14a.mov

### Detailed test instructions:

1. Install WC 6.7 beta-1 or beta-2
2. Check that in Edit Free Listings Page, the navigation as well as the continue button doesn't work. 
3. Checkout this PR
4. See that when no changes happened you can navigate using the top left navigation arrow
5. See that when changes happened a prompt appears when you navigate back using the top left navigation arrow
6. Same behaviour with top stepper navigation
7. Check that the button Conintue works without asking for any confirmation
8. Check that in step 2 it has the same behaviour
9. Check the Continue/back buttons in Setup Ads as well.
10. Roll back to WC < 6.7, for example 6.6
11. The UI has the same behaviour as 6.7 
12. Check other browsers like Mozilla Firefox

### Additional details:
Happy to hear alternative solutions for this 

### Changelog entry

> Fix - Compatibility with History Navigation v5

### CODE REVIEW

File: js/src/hooks/useNavigateAwayPromptEffect.js [hunk 1]
```diff
@@ -18,32 +18,38 @@ export default function useNavigateAwayPromptEffect(
...
-			// Chrome requires returnValue to be set.
-			e.returnValue = message;
-		};
+		// Block woocommerce/navigation in order to show a confirmation prompt in case shouldBlock is true
+		const unblock = getHistory().block( ( transition ) => {
+			let shouldUnblock = true;
 
-		if ( shouldBlock ) {
-			window.addEventListener( 'beforeunload', eventListener );
-		}
```
Comment (tomalec) [inline js/src/hooks/useNavigateAwayPromptEffect.js]: :question: 
Does your change still support non `woocommerce/navigation` links and reloads with v4?

Comment (puntope) [reply js/src/hooks/useNavigateAwayPromptEffect.js]: It works with WC 6.6. As far as I know it uses v4.

**Comment by tomalec** [comment]
This PR changes the behavior from using the native `beforeunload` event to custom re-implementation with` window.prompt`.
In general, I think re-implementing native features is asking for trouble, more maintenance and bugs.

:construction: Like here, now we lost the prompt on tab close.

### Steps to reproduce:
1. Go to edit free listings page `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&subpath=%2Ffree-listings%2Fedit`
2. Do a change
3. Click in browser's chrome to close the tab or reload the page
4. :red_circle: You should get the confirmation prompt

(tested with WC 6.5.0)

File: js/src/hooks/useNavigateAwayPromptEffect.js (hunk 1 above)
Comment (tomalec) [reply js/src/hooks/useNavigateAwayPromptEffect.js]: Seems reloads and tab closes does not work https://github.com/woocommerce/google-listings-and-ads/pull/1580#issuecomment-1176453957

**Comment by tomalec** [comment]
In 6.7 it works well. So maybe we could bump the minimum WC version to one that works fine. But still, I won't feel confident, as I don't know why it works in WC6.7. Who sets `beforeunload` event there? Is it consistently the `woocommerce/navigation` or is it just an accident it works, and may unexpectedly break in the future?

It's not us here. https://github.com/woocommerce/google-listings-and-ads/pull/1580/files#diff-c5eeef8e0b7c928685451e80738da84992a6b1670f323beadce101e97277a9bbR23 is not hit on page reload even in WC 6.7

File: js/src/hooks/useNavigateAwayPromptEffect.js (hunk 1 above)
Comment (puntope) [reply js/src/hooks/useNavigateAwayPromptEffect.js]: Fixed here (Tested in WC 6.5, WC 6.6 & WC 6.7)   https://github.com/woocommerce/google-listings-and-ads/pull/1580/commits/f5c84ca525c25b2622338e52747c0c3962fd9c95

Thanks for the catch btw

File: js/src/hooks/useNavigateAwayPromptEffect.js [hunk 2]
```diff
@@ -18,27 +18,45 @@ export default function useNavigateAwayPromptEffect(
...
-			// TODO: Consider being futureproof for history.v5 where
-			// getHistory().block( ( { location, retry } ) => {
+		// Block woocommerce/navigation in order to show a confirmation prompt in case shouldBlock is true
+		const unblock = getHistory().block( ( transition ) => {
+			let shouldUnblock = true;
 
-			// Return the message / truthy value to show a prompt.
+			if ( shouldBlock ) {
+				window.addEventListener( 'beforeunload', eventListener );
+			}
```
Comment (tomalec) [inline js/src/hooks/useNavigateAwayPromptEffect.js]: By moving `addEventListener` inside you lost the initial case

### Steps to reproduce
(exactly as in https://github.com/woocommerce/google-listings-and-ads/pull/1580#issuecomment-1176453957)
1. Go to edit free listings page `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&subpath=%2Ffree-listings%2Fedit`
2. Do a change
3. Click in browser's chrome to close the tab or reload the page
4. :red_circle: You should get the confirmation prompt


## What works
1. Go to edit free listings page `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fdashboard&subpath=%2Ffree-listings%2Fedit`
2. Do a change
3. Try navigating away with `< Edit free listings` button 
4. Cancel the prompt
5. Click in browser's chrome to close the tab or reload the page
6. :red_circle: You should get the confirmation prompt

Comment (puntope) [reply js/src/hooks/useNavigateAwayPromptEffect.js]: Which version are you testing? ITs working fine for me

File: js/src/hooks/useNavigateAwayPromptEffect.js [hunk 3]
```diff
@@ -18,27 +18,45 @@ export default function useNavigateAwayPromptEffect(
 	blockedLocation = () => true
 ) {
 	useEffect( () => {
-		// Bind beforeunload event for non `woocommerce/navigation` links and reloads.
-		// history#v5 does bind `beforeunload` automatically, with v4 we need to do it ourselves.
```
Comment (tomalec) [inline js/src/hooks/useNavigateAwayPromptEffect.js:22]: I'd keep that comment, as I believe it's still valid.

FWIW, reference to the latest `block` documentation that states it does register `beforeunload` https://github.com/remix-run/history/blob/main/docs/blocking-transitions.md#caveats

Comment (puntope) [reply js/src/hooks/useNavigateAwayPromptEffect.js:22]: Comment restored

File: js/src/hooks/useNavigateAwayPromptEffect.js (hunk 2 above)
Comment (puntope) [reply js/src/hooks/useNavigateAwayPromptEffect.js]: WC 6.5

https://user-images.githubusercontent.com/5908855/177748956-e0570094-e0fb-4f3b-9ac6-cd6d2e56431d.mov


WC 6.7

https://user-images.githubusercontent.com/5908855/177749839-9cfd5657-8ccb-4ee0-ac1c-55d7be008d26.mov

File: js/src/hooks/useNavigateAwayPromptEffect.js (hunk 3 above)
Comment (tomalec) [reply js/src/hooks/useNavigateAwayPromptEffect.js:22]: :nail_care: :nail_care: Initially I made it `//` not `/**`. Not to put it in `eventListener` function description, but rather a comment on the entire section that defines the function, **and actually binds it**. The function itself does not bind a thing, just prevents unload and returns the message.

**Review by tomalec — APPROVED** [review]
Reviewed the code, tested locally in WC 6.5 and 6.7 LGTM thanks
