### PR TITLE
Fix error displayed when accessing campaign assets editing page without attached asset groups

### LINKED ISSUE #2791: Error displayed when accessing campaign assets editing page without attached asset groups
### Describe the bug:

I found this issue when I was doing WC 9.7 compatibility testing. From the [smoke test wiki](https://github.com/woocommerce/google-listings-and-ads/wiki/Smoke-tests#google-listings--ads--dashboard) there is a test step:

> An empty asset group is created first when saving assets to a campaign that doesn't have any (empty) asset groups:
>
> a. In GLA, create a campaign without assets.
> b. Go to [Google Ads](https://ads.google.com/aw/campaigns) to delete the empty asset group for the newly created campaign.
> c. Back to GLA, refresh the web page, and go to edit the newly created campaign.
> d. Add assets and save changes.

An error page with the copy "Oops, something went wrong" appears when entering the asset editing page:

https://github.com/user-attachments/assets/7f798557-2128-4f34-b1e6-6db0f1a65f6e

This was introduced [since G4W 2.9.5](https://github.com/woocommerce/google-listings-and-ads/commit/87669b4700fa61a08f7e9677ef95e3325429f2bf#diff-e0dccb5ed2ae464fa5d0a3ce4f0619dd82f01a0ff01d7e112541181e8fb057bcR171), I think it can be solved by simply adding a `?` after the variables `assetEntityGroup` and `allValues`.

### Steps to reproduce:

1. In GLA, create a campaign without assets.
2. Go to [Google Ads](https://ads.google.com/aw/campaigns) to delete the empty asset group for the newly created campaign.
3. Back to GLA, refresh the web page, and go to edit the newly created campaign.
4. Click "Continue" to enter assets editing page
5. The error appears

### Expected behavior:

The assets editing page should be displayed correctly and the assets can be added and sync to Google Ads.

### Actual behavior:

The error displayed when accessing campaign assets editing page without attached asset groups.

### PR DESCRIPTION
**Pull request by ianlin**
### Changes proposed in this Pull Request:

Closes #2791.

This PR fixes an issue that will display an error when accessing campaign asset editing page without attached asset groups.

### Screenshots:

Note that at the end of the video there is an error notice, which is not related to this PR. I will try to reproduce it and create a follow up issue for it.

https://github.com/user-attachments/assets/f7d28078-296b-48fc-90d5-bab5c8fd2d1d

### Detailed test instructions:

1. In GLA, create a campaign without assets.
2. Go to [Google Ads](https://ads.google.com/aw/campaigns) to delete the empty asset group for the newly created campaign.
3. Back to GLA, refresh the web page, and go to edit the newly created campaign.
4. Click "Continue" to enter assets editing page
5. The assets editing page should open correctly
6. Add assets and click `Save changes`
7. Go to [Google Ads](https://ads.google.com/aw/campaigns), the asset group should be created with right assets.

### Changelog entry

> Fix - Error displayed when accessing campaign assets editing page without attached asset groups

### CODE REVIEW

File: js/src/pages/edit-paid-ads-campaign/index.js [hunk 1]
```diff
@@ -168,7 +168,7 @@ const EditPaidAdsCampaign = () => {
 		const hasChange =
 			allValues.amount !== campaign.amount ||
 			! isEqual(
-				assetEntityGroup.display_url_path,
+				assetEntityGroup?.display_url_path,
 				allValues.display_url_path
 			) ||
```
Comment (eason9487) [inline js/src/pages/edit-paid-ads-campaign/index.js]: In the case where the `assetEntityGroup` is undefined, this condition will cause the `hasChange` value to always be true before changing any campaign assets on UI.

image

After this condition can be correctly determined, the next line also triggers the same error as #2791.

https://github.com/woocommerce/google-listings-and-ads/blob/e95ac381d507143540db2798eac404c26a613ac4/js/src/pages/edit-paid-ads-campaign/index.js#L174

**Review by eason9487 — COMMENTED** [review]
Thanks for catching the issue and for the work!

It may need to take care of a few side effects after the change.

File: js/src/pages/edit-paid-ads-campaign/index.js (hunk 1 above)
Comment (ianlin) [reply js/src/pages/edit-paid-ads-campaign/index.js]: Thanks for catching this bug, I should've done more tests on it. I've added one commit to address it and it's ready for another round.

**Review by eason9487 — APPROVED** [review]
Thanks for the fix! LGTM.
