### PR TITLE
Fix retries when updating products

### LINKED ISSUE #1239: Update retry fails to schedule retry when internal errors occur
### Describe the bug:

When we update a product and we receive an internal error response we reschedule the product to be retried by calling the action hook `woocommerce_gla_batch_retry_update_products`. However the function `can_schedule` is called first to check if there is already an action scheduler task with the same hook name and the same list of arguments which is running.

So if we get a scenario where the same product fails repeatedly, it will end up calling the action `woocommerce_gla_batch_retry_update_products` while it's running a scheduled action with the same hook and list of arguments, preventing it to be scheduled for a retry.

This will only occur if the same product gets an internal error repeatedly. Internal errors in the Google API are not common (based on the logs), so I'm marking this issue as low priority.

PR #1238 fixes the same issue by checking with `did_action` if the retry action was called, and if so it will reschedule after one minute. We can use the same logic here for retrying an update after failure.

### Steps to reproduce:

To reproduce we would need to simulate error responses from the Google API, one solution for that is to use our test proxy, but it would need to be expanded to return errors on update. See instructions in #1238 for how the test proxy was used.

### PR DESCRIPTION
**Pull request by message-dimke**
### Changes proposed in this Pull Request:

Closes #1239 .

The task in the initial issue was to limit the amount of retries so if we would receive internal errors it wouldn't endlessly retry. However after additional testing it appears the `can_schedule` will check if there is a scheduled task running with the same hook name and the same list of arguments. When we call the action `woocommerce_gla_batch_retry_update_products` we are still running the scheduled task with the same hook name. So if all the products in the update batch fail we will have the same list of arguments and the retry will not be scheduled. This can occur easier if we are only updating one product at a time (for example when we set a single product to not sync or show, or it goes out of stock).

So this PR changes the following things:

- Always reschedule when we called the action `woocommerce_gla_batch_retry_update_products`
- Reschedule a retry after 1 minute (no use to retry an internal error right away)
- Limit retries to the product syncer threshold (5 tries)
- Add unit tests

### Screens:

WooCommerce_status_‹_Woo_s_👾_Commerce_—_WordPress

### Detailed test instructions:

Since we can't simulate internal errors in the Google API's we will need to test this PR with our test proxy in the `update_error` mode so it can return mocked error responses. If you are using **Docker see instructions** [here](https://github.com/woocommerce/google-listings-and-ads/blob/develop/tests/proxy/proxy.md#connect-test-site-to-proxy) on how to get it running.

- Run the proxy with a command like: ```PROXY_MODE=update_error cd tests/proxy && npm run test-proxy```
- Use a code snippet to get our site to connect to the proxy:
`define( 'WOOCOMMERCE_GLA_CONNECT_SERVER_URL', 'http://localhost:5500' );`
- Connect your Merchant account and sync all or some products (ensure we waited for the syncing to complete)
- Edit one of the synced products and mark it as "Sync and show" and save it
- This will trigger a product update, since we mocked the errors it will trigger a retry until it reaches the threshold of 5
- Wait for at least 6 minutes till it completes all the retries
- View the GLA log file in WooCommerce > Status > Logs
- Confirm that you see 4 failures in the log with a message like (the 5th time it won't be retried so it will only show debug messages that it failed):
```
2022-03-21T09:54:17+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_update_errors Internal API errors while submitting the following products: 33
```
- Check in WooCommerce > Status > Scheduled Actions and confirm that we have no more pending actions with the hook `gla/jobs/update_products/process_item`
- If we check the completed actions we will see 5 with the hook `gla/jobs/update_products/process_item`

### Changelog entry

- Fix - Limit failed update retries to 5 and schedule again after one minute.

### CODE REVIEW

File: src/Product/ProductSyncer.php [hunk 1]
```diff
@@ -271,7 +271,19 @@ public static function get_hidden_product_types(): array {
...
 	protected function handle_update_errors( array $invalid_products ) {
-		$error_products = $this->batch_helper->get_internal_error_products( $invalid_products );
+		$error_products = [];
+		foreach ( $invalid_products as $invalid_product ) {
+			if ( $invalid_product->has_error( GoogleProductService::INTERNAL_ERROR_REASON ) ) {
+				$wc_product_id = $invalid_product->get_wc_product_id();
+				$wc_product    = $this->wc->maybe_get_product( $wc_product_id );
+				// Only schedule for retry if the failure threshold has not been reached.
+				if ( ! $this->product_helper->is_update_failed_threshold_reached( $wc_product ) ) {
+					$product_id                    = $invalid_product->get_wc_product_id();
```
Comment (mikkamp) [inline src/Product/ProductSyncer.php]: We already saved this value in `$wc_product_id` on line 277, can we reuse that variable?

File: src/Product/ProductSyncer.php [hunk 2]
```diff
@@ -271,7 +271,19 @@ public static function get_hidden_product_types(): array {
 	 * @param BatchInvalidProductEntry[] $invalid_products
 	 */
 	protected function handle_update_errors( array $invalid_products ) {
-		$error_products = $this->batch_helper->get_internal_error_products( $invalid_products );
+		$error_products = [];
+		foreach ( $invalid_products as $invalid_product ) {
+			if ( $invalid_product->has_error( GoogleProductService::INTERNAL_ERROR_REASON ) ) {
+				$wc_product_id = $invalid_product->get_wc_product_id();
+				$wc_product    = $this->wc->maybe_get_product( $wc_product_id );
```
Comment (mikkamp) [inline src/Product/ProductSyncer.php:278]: `maybe_get_product` can return null (if it gets deleted right after it was scheduled to update). Can we check it's a valid product in the if clause?

File: tests/Unit/Jobs/UpdateProductsTest.php [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+			->method( 'schedule_single' )
+			->with(
+				$this->greaterThan( 0 ),
+				self::PROCESS_ITEM_HOOK,
+				[ $ids ]
+			);
+
+		do_action( 'woocommerce_gla_batch_retry_update_products', [] );
+
+		$this->job->schedule( [ $ids ] );
```
Comment (mikkamp) [inline tests/Unit/Jobs/UpdateProductsTest.php]: Normally the schedule function would be attached to the hook, so if we want to retry we pass the list of ids directly to the action and don't call the schedule function.

```suggestion
		do_action( 'woocommerce_gla_batch_retry_update_products', $ids );
```

In order for that to work we need to call some of the code in [`JobInitializer::register`](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/Jobs/JobInitializer.php#L51-L58). I wouldn't suggest to mock up the JobInitializer but maybe we can go for something simple like this in the setUp function to attach the start hooks:
```php
add_action(
	$this->job->get_start_hook()->get_hook(),
	function ( ...$args ) {
		$this->job->schedule( $args );
	},
	10,
	$this->job->get_start_hook()->get_argument_count()
);
``` 
Or we could add it to a JobTrait in tests/Tools/HelperTrait since we might want to reuse it for testing other jobs with start hooks.

**Review by mikkamp — COMMENTED** [review]
Thanks for the changes, they are working as intended and I get the expected results in my log files. I just left some smaller comments on a few things I noticed. I think especially for the test it would be nice to attach those hooks to be able to match the real class. It's a nice touch adding the unit tests, that was needed.

File: tests/Tools/HelperTrait/JobTrait.php [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+ *
+ * @package Automattic\WooCommerce\GoogleListingsAndAds\Tests\Tools\HelperTrait
+ */
+trait JobTrait {
+
+	/**
+	 * Adding Job start hook
+	 */
+	protected function add_job_start_hook() {
+		$this->job->init();
```
Comment (mikkamp) [inline tests/Tools/HelperTrait/JobTrait.php]: Have mixed feelings about adding this in a function called `add_job_start_hook`, because it's only for jobs that implement `StartOnHookInterface`. But since it's just for testing it's not a big deal.

**Review by mikkamp — APPROVED** [review]
Thanks for the changes, it's looking good and all the tests pass.
Just left one comment, but it's not a big deal to leave it as is.
