### PR TITLE
Use task list API for checking if we should show tasks list.

### LINKED ISSUE #1054: Depreciated warning of `should_show_tasks`
### Describe the bug:
There is a depreciated warning of `should_show_tasks` when enabling the Google Listings & Ads plugin

Screen Shot 2021-10-18 at 9 35 48 AM

### Expected behavior:
Should not log the depreciated warning.

### Actual behavior:
A depreciated function is called in the `TaskListTrait` -> https://github.com/woocommerce/google-listings-and-ads/blob/develop/src/TaskList/TaskListTrait.php#L21-L23

### Steps to reproduce:
1. Install WC 5.8 and install the Google Listings & Ads plugin
2. Go to WooCommerce > Home having finished the onboarding wizard
3. If `WP_DEBUG` is enabled, notice the warning in the dashboard, otherwise see the warning in `debug.log`

### LINKED ISSUE #1080: WC 5.9 compatibility - migrate should_show_tasks to task list API.
### Describe the bug:
In WC5.9 the `should_show_tasks` method was deprecated. We should use task list API instead. For reference https://github.com/woocommerce/woocommerce-admin/pull/7577
<figure class="wp-block-table" style="box-sizing: border-box; border: 0px; font-family: inter, -apple-system, system-ui, blinkmacsystemfont, &quot;Segoe UI&quot;, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-weight: 400; margin: 0px 0px 1.8em; outline: 0px; padding: 0px; vertical-align: baseline; display: block; overflow-x: auto; color: rgb(0, 16, 28); font-size: 16px; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Type | File | Line | Notice | Function / Method
-- | -- | -- | -- | --
method_deprecated | src/TaskList/TaskListTrait.php | 22 | Class method \Automattic\WooCommerce\Admin\Features\Onboarding::should_show_tasks() is deprecated woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php line 367 | \Automattic\WooCommerce\Admin\Features\Onboarding::should_show_tasks()

</figure><br class="Apple-interchange-newline">

It looks like a good old version compare will be required.
### Expected behavior:
No deprecation logs.

### Steps to reproduce:

I have not tested this yet. I am just writing what compat checker has found.

### Additional details:
Found during WC5.9 compatibility testing.

### PR DESCRIPTION
**Pull request by budzanowski**
### Changes proposed in this Pull Request:

Use Task list API in place for the now deprecated `Onboarding::should_show_tasks()`

Closes #1080 and #1054 .

_Replace this with a good description of your changes & reasoning._

### Detailed test instructions:

1.  🤷🏻 

### Changelog entry

> Update - Use Task List API to detect if we should register tasks.

### CODE REVIEW

**Review by layoutd — APPROVED** [review]
👍🏻  LGTM - removes the deprecation warning with WC 5.9 and still works with 5.8.

I also added that this closes issue #1054 which seems to be the same as 1080.

There does appear to be a JS issue with the onboarding task list in the `develop` branch, I've logged it as an issue here:  https://github.com/woocommerce/google-listings-and-ads/issues/1085

File: google-listings-and-ads.php [hunk 1]
```diff
@@ -8,7 +8,7 @@
  * Author URI: https://woocommerce.com/
  * Text Domain: google-listings-and-ads
  * Requires at least: 5.6
- * Tested up to: 5.8
+ * Tested up to: 5.9
```
Comment (ecgan) [inline google-listings-and-ads.php:11]: This was bumping WP version to 5.9, not the intended WC version.

File: readme.txt [hunk 2]
```diff
@@ -2,7 +2,7 @@
 Contributors: automattic, google, woocommerce
 Tags: woocommerce, google, listings, ads
 Requires at least: 5.5
-Tested up to: 5.8
+Tested up to: 5.9
```
Comment (ecgan) [inline readme.txt:5]: This was also bumping WP version to 5.9, not the intended WC version.

**Review by ecgan — COMMENTED** [review]
Just noticed that we were accidentally bumping WP version, instead of WC version.
