### PR TITLE
Fix the issue that all data on the report pages are not shown

### LINKED ISSUE #1183: All data on programs and products report pages are not shown
### Describe the bug:

This was introduced by #1151. And this problem has **NOT** been released yet. 🤞 

image

The root cause is the `'[indexName]'` format of `path` arguments when using `lodash.setWith()`. it means setting the next nested layer of object or array by the index of `'indexName'`.

And the [`getReportKey`](https://github.com/woocommerce/google-listings-and-ads/blob/f75f58f9d98c6e929f1a420d6e557932b73a55b2/js/src/data/utils.js#L97-L100
) will generate the `path` string based on JSON format with `[` and`]`. For example:
```json
{"after":"2021-01-01","before":"2021-01-07","fields":["sales","conversions","spend","clicks","impressions"],"interval":"day","order":"desc","orderby":"sales"}
```

Then leads to the reducer creating the state tree in the incorrect structure.

image

### Expected behavior:

All report data should be rendered.

### Actual behavior:

Nothing is rendered when there're report data.

### Steps to reproduce:

1. Add snippets in the **google-listings-and-ads.php** file if you don't have report data to check it.
    ```php
    add_filter(
    	'woocommerce_gla_prepared_response_mc-reports-programs',
    	function( $response ) {
    		return json_decode( file_get_contents( __DIR__ . '/tests/mocks/mc/reports/programs.json' ), true ) ?: [];
    	},
    );
    
    add_filter(
    	'woocommerce_gla_prepared_response_ads-reports-programs',
    	function( $response ) {
    		return json_decode( file_get_contents( __DIR__ . '/tests/mocks/ads/reports/programs.json' ), true ) ?: [];
    	},
    );
    ``` 
2. Go to the programs report page `/wp-admin/admin.php?page=wc-admin&reportKey=programs&path=%2Fgoogle%2Freports`.
3. Nothing is renedered.

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

Closes #1183

- Make `path` argument of `chain` and `set` functions accept array type to fix the incorrect path parsing issue of report data in the reducer.
- Extra change: Change the dynamic storing paths of MC product feed to use array `path` to make it look clearer in the reducer.
- Extra change: Add the **.externalized.json** file to the ignored watching patterns of jest to avoid repeatedly running the same test after modifying js file.

### Screenshots:

image

#### The report page

1. Add snippets in the **google-listings-and-ads.php** file if you don't have report data to check it.
    ```php
    add_filter(
    	'woocommerce_gla_prepared_response_mc-reports-programs',
    	function( $response ) {
    		return json_decode( file_get_contents( __DIR__ . '/tests/mocks/mc/reports/programs.json' ), true ) ?: [];
    	},
    );
    
    add_filter(
    	'woocommerce_gla_prepared_response_ads-reports-programs',
    	function( $response ) {
    		return json_decode( file_get_contents( __DIR__ . '/tests/mocks/ads/reports/programs.json' ), true ) ?: [];
    	},
    );
    ``` 
2. Go to the programs report page `/wp-admin/admin.php?page=wc-admin&reportKey=programs&path=%2Fgoogle%2Freports`.
3. Data in the chart and **Program** table should be displayed.

#### The product feed page

1. Go to the programs report page `/wp-admin/admin.php?page=wc-admin&reportKey=programs&path=%2Fgoogle%2Fproduct-feed`.
2. Data in the **Issues to resolve** table should be displayed as before.

### CODE REVIEW

File: js/src/data/reducer.js [hunk 1]
```diff
@@ -46,10 +46,19 @@ function chain( state, basePath = '' ) {
...
 	};
+	const combinBasePath = ( path ) => {
+		if ( basePath ) {
+			if ( Array.isArray( basePath ) || Array.isArray( path ) ) {
+				return [].concat( basePath, path );
+			}
+			return `${ basePath }.${ path }`;
+		}
+		return path;
+	};
```
Comment (ianlin) [inline js/src/data/reducer.js]: 💅  This function returns a `string` or an `array` and it took me a while to understand it's because lodash `setWith` 's second parameter `path` can be either a string or an array. Might be better to add a comment here 😃

**Review by ianlin — APPROVED** [review]
Tested locally and everything works as expected. 👍 

✅  I can reproduce it using the `develop` branch, none is rendered in the reports page.
✅  Using this PR's branch, I can see the data rendered in the chart and the Program table.
✅  Using this PR's branch, I can see the **Issues to resolve table** is displayed normally.
✅  The newly added unit test can catch the error using the code in `develop` branch.

File: js/src/data/reducer.js [hunk 2]
```diff
@@ -46,10 +46,19 @@ function chain( state, basePath = '' ) {
 		}
 		return clone( value );
 	};
+	const combinBasePath = ( path ) => {
```
Comment (jorgemd24) [inline js/src/data/reducer.js]: ❔

Is it needed to put this function inside of the `chain function` scope? I think we could just have this function outside of the `chain function` scope receiving two params: `basePath` and `path` thus it could be re-used easily in the future.

💅  I think there is a misspelling with the function's name `combinBasePath` should be `combineBasePath`

File: js/src/data/reducer.js [hunk 3]
```diff
@@ -46,10 +46,19 @@ function chain( state, basePath = '' ) {
...
+			if ( Array.isArray( basePath ) || Array.isArray( path ) ) {
+				return [].concat( basePath, path );
+			}
+			return `${ basePath }.${ path }`;
+		}
+		return path;
+	};
 
 	return {
 		set( path, value ) {
```
Comment (jorgemd24) [inline js/src/data/reducer.js:93]: ❔ 

This is not related to this PR but sometimes I get confused with the `set function` that has the same name as [lodash set](https://lodash.com/docs/4.17.15#set) and it can be easily mistaken.

Comment (eason9487) [reply js/src/data/reducer.js:93]: Thanks for pointing out this. What about changing `set` to `setIn`, and `chain` to `chainState`? And I lean toward renaming them in a separate RP.

File: js/src/data/reducer.js (hunk 1 above)
Comment (eason9487) [reply js/src/data/reducer.js]: Added by https://github.com/woocommerce/google-listings-and-ads/pull/1184/commits/eb552c08e0536aca8a76718651d47997cafb8ec3.

File: js/src/data/reducer.js (hunk 2 above)
Comment (eason9487) [reply js/src/data/reducer.js]: Thanks for catching the typo. Fixed by https://github.com/woocommerce/google-listings-and-ads/pull/1184/commits/6534674b77c9cf934f7467e93b15d17c58485c41.

> Is it needed to put this function inside of the `chain function` scope? I think we could just have this function outside of the `chain function` scope receiving two params: `basePath` and `path` thus it could be re-used easily in the future.

I guess its reuse is likely to be relatively low. I'd prefer to move it out when the needs happen.

File: js/src/data/reducer.js (hunk 3 above)
Comment (jorgemd24) [reply js/src/data/reducer.js:93]: Yes, those names are better and it will help to avoid any confusion with lodash. Thanks!

File: js/src/data/reducer.js (hunk 2 above)
Comment (jorgemd24) [reply js/src/data/reducer.js]: Thanks for correcting this! 

> I guess its reuse is likely to be relatively low. I'd prefer to move it out when the needs happen.

Let's keep it as it is so we do not delay this PR and if in the future is needed we can just move it out.

File: js/src/data/reducer.js (hunk 3 above)
Comment (eason9487) [reply js/src/data/reducer.js:93]: The follow-up PR: #1191
