### PR TITLE
Fix the incorrect enabled state after removing a disabled program from the programs table

### LINKED ISSUE #762: Incorrect enabled states on the programs table after removing a disabled program
### Describe the bug:

On the Dashboard page, after removing a disabled program, other programs might display a wrong enabled state.

### Expected behavior:

After removing a disabled program, the rest of programs should have the same enabled states.

### Steps to reproduce:

1. Create at least two paid programs
2. Disabled the program at the top of the programs table and then remove it.
3. The enabled state of the program, which is under that removed program, will be changed to disabled

Kapture 2021-06-08 at 11 27 04

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

Closes #762 

Changes to the programs table on the Dashboard page

- Fix the incorrect enabled state after removing a disabled program
- Bonus: cancel the focus from the "Remove" links after removing a program

#### The enabled states are correct after the remove

Kapture 2021-06-09 at 16 03 32

#### Cancel the focus

image

In the first demo GIF, the focus is locating to the next "Remove" link after the remove. This demo GIF shows that the https://github.com/woocommerce/google-listings-and-ads/commit/82975fe46348c6fce0b8ab1f890b3ee4ccc2301f was to fix this minor issue.

Kapture 2021-06-09 at 16 03 40

### Detailed test instructions:

1. Create at least two paid programs
2. Disabled the program at the top of the programs table and then remove it
3. The enabled state of the program, which is under that removed program, should be the correct state

### Changelog entry

- The incorrect enabled state after removing a disabled program from the programs table
- Cancel the focus from the "Remove" links after removing a program from the programs table

### CODE REVIEW

File: js/src/dashboard/all-programs-table-card/index.js [hunk 1]
```diff
@@ -113,15 +113,18 @@ const AllProgramsTableCard = ( props ) => {
...
 							<div className="program-actions">
 								<EditProgramButton programId={ el.id } />
 								{ el.id !== FREE_LISTINGS_PROGRAM_ID && (
-									<RemoveProgramButton programId={ el.id } />
+									<RemoveProgramButton
+										key={ el.id }
+										programId={ el.id }
+									/>
 								) }
 							</div>
```
Comment (ecgan) [inline js/src/dashboard/all-programs-table-card/index.js]: 💅  Instead of putting `key={ el.id }` at the `RemoveProgramButton`, I would put it at the top-most `div` wrapping everything inside.

**Review by ecgan — APPROVED** [review]
LGTM, tested locally, seems working good. 👍  Just left one minor nitpick comment.

**Comment by ecgan** [comment]
Just FYI for reference, I was wondering what causes the issue and why specifying the `key` would solve the issue. Turns out, I think it was because of `@woocommerce/components`'s `Table` component rendering rows using array index as keys, which could give us this kind of problem when adding/removing rows.

https://github.com/woocommerce/woocommerce-admin/blob/66cdf344ea615e451428bb8c419f974cf413a44a/packages/components/src/table/table.js#L288-L289

**Comment by eason9487** [comment]
> Turns out, I think it was because of `@woocommerce/components`'s `Table` component rendering rows using array index as keys, which could give us this kind of problem when adding/removing rows.

Indeed. In most cases, the array indices aren't the proper keys when rendering component array. And that's one of the examples of misuse.

File: js/src/dashboard/all-programs-table-card/index.js (hunk 1 above)
Comment (eason9487) [reply js/src/dashboard/all-programs-table-card/index.js]: Moved by https://github.com/woocommerce/google-listings-and-ads/pull/771/commits/77848d9714f4ecff3be1150be85ed144a6c5a5ea and added comments for this fix.
