### PR TITLE
Fix issues and react warnings for verification code components

### LINKED ISSUE #1002: First number of phone verification is not cleared when clicking "Resend…" button
_(This is a belated follow up from https://github.com/woocommerce/google-listings-and-ads/pull/993)_
### Describe the bug:
When I click "Resend code" button all the inputs are cleared except the first one, then the number is cleared when I move the focus away.

first

### Expected behavior:
All numbers should be cleared.

### Actual behavior:
The first one is still there.

### Steps to reproduce:

1. Go to phone verification settings [`/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings`](https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings)
2. Click "Send verification code"
3. Type `123456`
4. Click "Resend code" (once ready)
5. :red_square: the `1` is still there
6. Click somewhere, to move focus away from the focused first field.

### LINKED ISSUE #1003: Backspace does not remove selected verification code number
_(This is a belated follow up from https://github.com/woocommerce/google-listings-and-ads/pull/993)_
### Describe the bug:
When I select a number and click <kbd>backspace</kbd>, the focus is moved back, but the number is not removed.

### Expected behavior:

Backspace removes the selection and moves the caret back(left).

### Actual behavior:
Caret Is moved, but the number is not deleted.

### Steps to reproduce:

1. Go to phone verification settings [`/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings`](https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings)
2. Click "Send verification code"
2. Input `123456`
3. Select any number from 2-6
3. Click <kbd>backspace</kbd>

backspace

This is even more disturbing when navigating the using keyboard-only:

3. Input `123456`
4. Click <kbd>tab</kbd>
5. Click <kbd>shift + tab</kbd>
6. Click <kbd>backspace</kbd>

backspace2

### LINKED ISSUE #1004: React warning is thrown when leaving phone verification.
### Describe the bug:

React warns: `Can't perform a React state update on an unmounted component` when you leave the phone verification component while the verification process/promise is pending.

### Expected behavior:
No warning should be thrown.

### Actual behavior:
React throws:
reaxct state

<details>
<summary><code>Can't perform a React state update on an unmounted component</code></summary>

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in VerifyPhoneNumberContent (created by DemoVerifyPhoneNumberCard)
    in div (created by Context.Consumer)
    in CardUI (created by Card)
    in Card (created by Card)
    in Card (created by AccountCard)
    in AccountCard (created by DemoVerifyPhoneNumberCard)
    in div (created by DemoVerifyPhoneNumberCard)
    in section (created by DemoVerifyPhoneNumberCard)
    in DemoVerifyPhoneNumberCard (created by Settings)
    in div (created by Settings)
    in Settings (created by ee)
    in Suspense (created by ee)
    in ee (created by bt)
    in div (created by bt)
    in div (created by ht)
    in ht (created by bt)
    in div (created by bt)
    in slot_fill_provider_SlotFillProvider (created by Provider)
    in provider_SlotFillProvider (created by Provider)
    in Provider (created by bt)
    in bt
    in Unknown (created by WithSelect(bt))
    in WithSelect(bt) (created by WithPluginsHydration(WithSelect(bt)))
    in WithPluginsHydration(WithSelect(bt)) (created by Context.Consumer)
    in t
```
</details>

<details>
<summary><code>Warning: Each child in a list should have a unique "key" prop.</code></summary>

```
react_devtools_backend.js:4049 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ForwardRef(Button)`. It was passed a child from AppButton. See https://fb.me/react-warning-keys for more information.
    in Qc (created by AppButton)
    in ForwardRef(Button) (created by AppButton)
    in AppButton (created by VerifyPhoneNumberContent)
    in div (created by Context.Consumer)
    in Flex (created by ForwardRef(FlexComponent))
    in ForwardRef(FlexComponent) (created by VerifyPhoneNumberContent)
    in div (created by Subsection)
    in Subsection (created by VerifyPhoneNumberContent)
    in div (created by Context.Consumer)
    in BodyUI (created by CardBody)
    in CardBody (created by Body)
    in Body (created by VerifyPhoneNumberContent)
    in VerifyPhoneNumberContent (created by DemoVerifyPhoneNumberCard)
    in div (created by Context.Consumer)
    in CardUI (created by Card)
    in Card (created by Card)
    in Card (created by AccountCard)
    in AccountCard (created by DemoVerifyPhoneNumberCard)
    in div (created by DemoVerifyPhoneNumberCard)
    in section (created by DemoVerifyPhoneNumberCard)
    in DemoVerifyPhoneNumberCard (created by Settings)
    in div (created by Settings)
    in Settings (created by ee)
    in Suspense (created by ee)
    in ee (created by bt)
    in div (created by bt)
    in div (created by ht)
    in ht (created by bt)
    in div (created by bt)
    in slot_fill_provider_SlotFillProvider (created by Provider)
    in provider_SlotFillProvider (created by Provider)
    in Provider (created by bt)
    in bt
    in Unknown (created by WithSelect(bt))
    in WithSelect(bt) (created by WithPluginsHydration(WithSelect(bt)))
    in WithPluginsHydration(WithSelect(bt)) (created by Context.Consumer)
    in t
    in t
    in t
    in Unknown (created by WithOptionsHydration(Component))
    in WithOptionsHydration(Component) (created by WithSettingsHydration(WithOptionsHydration(Component)))
    in WithSettingsHydration(WithOptionsHydration(Component)) (created by WithSettingsHydration(WithSettingsHydration(WithOptionsHydration(Component))))
    in WithSettingsHydration(WithSettingsHydration(WithOptionsHydration(Component))) (created by WithCurrentUserHydration(WithSettingsHydration(WithSettingsHydration(WithOptionsHydration(Component)))))
    in WithCurrentUserHydration(WithSettingsHydration(WithSettingsHydration(WithOptionsHydration(Component))))
```
</details>

### Steps to reproduce:

1. Go to phone verification settings [`/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings`](https://gla1.test/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fsettings)
2. Click "Send verification code"
2. Input `123456`
3. Navigate away

### Additional details:
- I guess `Each child in a list should have a unique "key" prop` is a separate issue for the `Button` itself, but was not sure.
- Seems to be related to my doubt about promise handling in https://github.com/woocommerce/google-listings-and-ads/pull/993#discussion_r703846809

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

Closes #1002, #1003, #1004

- https://github.com/woocommerce/google-listings-and-ads/commit/305c21c4e0fa92ea25bd3f301a7be3b1bfe3777d - Fix that the first verification code input isn't cleared after reset.
- https://github.com/woocommerce/google-listings-and-ads/commit/2188f6075aac882330a7f327a5ed10d5325fac9d - Fix that backspace doson't remove selected digit in the `<VerificationCodeControl>`.
- https://github.com/woocommerce/google-listings-and-ads/commit/49371b518e96d4babc1d135d26e14ff06a9d55e0 - Fix the warning of updating state on an unmounted component.
- https://github.com/woocommerce/google-listings-and-ads/commit/8f8734125bfa81d4c4e3356315583cf6f14bbdc3 - Fix the warning of missing unique key in the `<AppButton>`.

### Additional notes

- [x] 📝  Revert https://github.com/woocommerce/google-listings-and-ads/commit/f605132381c0ff3494f8b4305c575381e2fa5c8c to removed `<DemoVerifyPhoneNumberCard>` before merging this PR.

#### #1002 - Clear input after reset

Kapture 2021-09-10 at 15 19 51

#### #1003 - Delete selected value when pressing backspace

Kapture 2021-09-10 at 15 16 42

#### #1004 - Fix react warnings

Kapture 2021-09-10 at 15 54 21

### Detailed test instructions:

1. Go to the Setting page and there's a demo component for testing
2. Follow the replication steps in each issue to check if they were fixed
    - #1002
    - #1003
    - #1004

### CODE REVIEW

File: js/src/hooks/useIsMounted.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+/**
+ * External dependencies
+ */
+import { useEffect, useCallback, useRef } from '@wordpress/element';
+
+/**
+ * Returns a function to check whether the caller component is mounted or unmounted.
+ * Usually, it's used to avoid the warning - Can't perform a React state update on an unmounted component.
+ *
+ * @return {() => boolean} A function returns a boolean indicates the caller component is mounted or unmounted.
```
Comment (tomalec) [inline js/src/hooks/useIsMounted.js]: :nail_care: 
I'm not born with English/English native, but Grammarly suggests:
```suggestion
 * @return {() => boolean} A function returns a boolean that indicates the caller component is mounted or unmounted.
```

File: js/src/hooks/useIsMounted.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+ */
+export default function useIsMounted() {
```
Comment (tomalec) [inline js/src/hooks/useIsMounted.js:12]: :grey_question: 
Looks like native [`Node.isConnected`](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected). I'm surprised that React does not have it somewhat built-in and we have to hand-craft it? Do we do something not popular/standard here?

File: js/src/components/contact-information/phone-number-card/verification-code-control.js [hunk 3]
```diff
@@ -103,18 +103,38 @@ export default function VerificationCodeControl( {
...
+	 *
+	 * @see https://github.com/WordPress/gutenberg/blob/%40wordpress/components%4012.0.8/packages/components/src/input-control/input-field.js#L73-L90
+	 *
+	 * And it's also used for the first time focus after this component being mounted.
+	 */
+	useEffect( () => {
+		if ( digits === initDigits ) {
+			maybeMoveFocus( 0 );
+		}
+	}, [ resetNeedle, digits ] );
```
Comment (tomalec) [inline js/src/components/contact-information/phone-number-card/verification-code-control.js]: 👍 Thanks for the detailed explanations :) It makes it clear why the code is here not where it was before. 
:nail_care: However, I think we could also add a note of why we need it at all/what it does, for somebody who reads the file as is, not as a change to the previous state.

I made a branch with a small proposal https://github.com/woocommerce/google-listings-and-ads/compare/fix/1002-1003-1004-verification-code...fix/1002-1003-1004-verification-code-comments, feel free to merge it if you like it :)

**Review by tomalec — APPROVED** [review]
Reviewed the code, tested locally on WP58 & WC57, LGTM.
Left few comments about cosmetics.

Thanks for the demo component, and detailed explanations.

File: js/src/components/contact-information/phone-number-card/verification-code-control.js (hunk 3 above)
Comment (eason9487) [reply js/src/components/contact-information/phone-number-card/verification-code-control.js]: Merged. Thanks!

File: js/src/hooks/useIsMounted.js (hunk 2 above)
Comment (eason9487) [reply js/src/hooks/useIsMounted.js:12]: > I'm surprised that React does not have it somewhat built-in and we have to hand-craft it?

It had had a similar API `isMounted`, but was deprecated. https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

> Do we do something not popular/standard here?

It is difficult to say whether this practice is popular/standard or not because it's not really an issue or bug in most cases when seeing that warning.

`useIsMounted` is here mainly to avoid that scary warning appearing, but in fact there's no memory leak problem nor additional side effects.

The warning has quite a long background, mainly because some earlier global store/state management libraries based on the "Flux Architecture" had subscription and unsubscription mechanisms to be plugged in the class components. As an observer to get the global state changes, if a component forgets to unsubscribe after unmounted, it might let the global store keep the reference of the component itself or the method declared within the component, which may further lead to memory leaks.

However, with the implementation of something like react-redux, these subscription processes have been replaced by Higher-Order Components (HOC) and the memory leak problem is no longer common. After react hooks, these warnings are also almost false positives alarm. As it turns out, [this warning will be adjusted in the new version of react](https://github.com/facebook/react/pull/22114), and we will no longer need `useIsMounted` then.
