### PR TITLE
Remove file autoloads for namespaced packages

### LINKED ISSUE #952: Guzzle conflict
Still getting a conflict with Guzzle after updating to 1.4.0. Having this plugin activated is throwing a Guzzle error with my application. 

PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\\choose_handler() in /nas/content/live/theflagstaging/wp-content/themes/twentyfifteen-child/vendor/guzzlehttp/guzzle/src/HandlerStack.php:42

Please let me know if I can provide any more information.

### PR DESCRIPTION
**Pull request by mikkamp**
### Changes proposed in this Pull Request:

We added the loading of the function_includes files directly to our [composer.json](https://github.com/woocommerce/google-listings-and-ads/blob/1.4.0/composer.json#L35-L39) file. Note that we need to load these files directly to support deprecated functions. The Google Ads library > GAX relies on some deprecated functions, so until that's updated we will need to resolve the conflict with any other plugins/themes that use deprecated functions.

The technique we use works great for `google-listings-and-ads` to enforce that the re-named versions are loaded. However loading from the main composer.json file, actually adds the files a second time to the `vendor/composer/autoload_files.php` file. The hash is generated with `package name + file path`, so even if it's already loaded by another plugin, we still load it with our GLA package name.
In the case of a theme (or a plugin which is loaded after ours) they are loaded later, so we claim both the hash `guzzlehttp/guzzle ... functions_include.php` and `woocommerce/google-listings-and-ads ... functions_include.php` which both load our namespaced versions. So any call to a deprecated function using the original namespace (GuzzleHttp) will fail.

So to summarize our method works if a plugin loads guzzle first and we load our namespaced version after, but the other way around, and the deprecated functions are missing (only loaded for our new namespace name).

Note: The scope of conflicts here is limited because both of the following requirements must be true.
- Plugin / theme is loaded after the `google-listings-and-ads` extension
- Plugin / theme uses deprecated Guzzle functions

What this PR does is update the file `vendor/composer/installed.json` and removes any `autoload > files`. In addition to this it checks to confirm that the file is included in the main composer.json file, if it is not it will fail with an error which must be fixed before composer install can be run.

Closes #952

Example theme which uses a deprecated function:
[storefront-child.zip](https://github.com/woocommerce/google-listings-and-ads/files/6975492/storefront-child.zip)

With `google-listings-and-ads` activated this child theme will fail with the error:

```
[12-Aug-2021 12:14:24 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\choose_handler() in wp-content/themes/storefront-child/functions.php:14
```

If we deactivate `google-listings-and-ads` it doesn't give any issues.

### Detailed test instructions:

1. Deactivate the `google-listings-and-ads` extension
2. Install the example child theme (needs storefront installed)
3. Run `composer install` within the child theme directory
4. Activate `google-listings-and-ads` and observe the fatal error
5. Checkout this PR
6. Run `rm -rf vendor && composer install`
7. Reactivate `google-listings-and-ads` and confirm that the fatal no longer occurs
8. Test some requests from the Connection Test page and confirm they complete without errors
9. In particular test the request "Get Campaigns from Google Ads" as this uses some deprecated functions from the Guzzle package

### Changelog entry
* Fix - Remove file autoloads for namespaced packages.

### CODE REVIEW

File: bin/prefix-vendor-namespace.php [hunk 1]
```diff
@@ -141,3 +147,50 @@ function replace_in_json_file( string $file, string $namespace, string $new_name
 		)
 	);
 }
+
+function remove_file_autoloads( string $file, array $composer_json, string $package_name ) {
```
Comment (JPry) [inline bin/prefix-vendor-namespace.php]: Minor: We're only using `$composer_json['autoload']['files']` in this function, so I think we should pass *only* that array instead of the entire `$composer_json`

File: bin/prefix-vendor-namespace.php [hunk 2]
```diff
@@ -141,3 +147,50 @@ function replace_in_json_file( string $file, string $namespace, string $new_name
...
+		}
+
+		if ( empty( $package['autoload']['files'] ) ) {
+			continue;
+		}
+
+		foreach( $package['autoload']['files'] as $autoload_file ) {
+
+			// Confirm we already include this autoload in the main composer file.
+			$filename = 'vendor/' . $package['name'] . '/' . $autoload_file;
```
Comment (JPry) [inline bin/prefix-vendor-namespace.php]: Minor: Let's use interpolation here instead of concatenation

```suggestion
			$filename = "vendor/{$package['name']}/{$autoload_file}";
```

File: bin/prefix-vendor-namespace.php [hunk 3]
```diff
@@ -141,3 +147,50 @@ function replace_in_json_file( string $file, string $namespace, string $new_name
 		)
 	);
 }
+
```
Comment (JPry) [inline bin/prefix-vendor-namespace.php:172]: Minor: For our own benefit, we should include a docblock describing what this function accomplishes.

**Review by JPry — APPROVED** [review]
I've done some testing of this PR, including looking at some other options for fixing this. I think this really is the most practical option, and it does work as described. 

I have a few minor changes suggested, but none of them are blocking.
