### PR TITLE
Compatibility between CES and WC7.3

### LINKED ISSUE #1836: Customer effort score prompt is showing undefined
### Describe the bug:

After completing setup onboarding and we get redirected to product feed page, the customer effort score prompt shows "undefined". When we click on the "Give feedback" button, the modal shows up with two rows of feedback response.

📹 Demo video of the issue:

https://user-images.githubusercontent.com/417342/210250194-10b227e8-f763-409f-8dd1-35a2e1d5eb39.mp4

I believe this issue is related to issue https://github.com/woocommerce/woocommerce/issues/35124 and PR https://github.com/woocommerce/woocommerce/pull/35680 where the CustomerEffortScore component has been changed. The PR is included in https://github.com/woocommerce/woocommerce/releases/tag/7.3.0-beta.1.

I can reproduce this issue using WooCommerce trunk branch (I tested with commit d4ce6faf1eaf40d45d339498cdb9c6badb5d28f2). I tried to test it with https://github.com/woocommerce/woocommerce/releases/tag/7.3.0-beta.2 and https://github.com/woocommerce/woocommerce/releases/tag/7.3.0-beta.1 but there are TypeScript build errors (see woo-monorepo slack message p1672670905755799-slack-C03CPM3UXDJ).

This issue does not happen with WC https://github.com/woocommerce/woocommerce/releases/tag/7.2.2. The following is a demo video using WC 7.2.2 and it shows CES working as expected, with label in the prompt, and title and question in the modal:

https://user-images.githubusercontent.com/417342/210254098-ed625087-9ffb-445a-b34a-1b7711c4f757.mp4

### Steps to reproduce:

Pre-condition: Use the abovementioned WooCommerce version.

To test this issue easily, you can modify the following line:

https://github.com/woocommerce/google-listings-and-ads/blob/161f254dc243b6967fbbe78be030d9ba500947a7/js/src/product-feed/index.js#L54

with:

```js
			{ ( true || canCESPromptOpen ) && (
```

to force the Customer Effort Score prompt to show up when you navigate to the Product Feed tab.

1. Navigate to Product Feed page: `/wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fproduct-feed`
2. You should see the issue as shown in the demo video.

### Expected behavior:

There should be a clear CES question in the prompt.

### Actual behavior:

The CES prompt says "undefined".

### PR DESCRIPTION
**Pull request by puntope**
### Changes proposed in this Pull Request:

Closes #1836 

This PR implements some new properties required in CES prompt under WC 7.3 to render properly. At the same time, it maintains compatibility with WC < 7.3

### Screenshots:

WC 7.3

https://user-images.githubusercontent.com/5908855/210545755-330d70af-5a5b-4eb5-83f0-43b90180e2a5.mov

WC 7.2

https://user-images.githubusercontent.com/5908855/210545265-6aa75fdb-db36-4185-a924-0a9b49abf151.mov

 
### Detailed test instructions:

1. Install WC 7.3beta 1 - https://github.com/woocommerce/woocommerce/releases/tag/7.3.0-beta.1
2. See the CES prompt renders with two questions and you can send the score and comment. (Only 1 question is being sent)
3. Install WC < 7.3 (for example 7.2) 
4. See the CES prompt renders with one question and you can send the score and comment.

### Additional details:

To test this issue easily, you can modify the following line:

[google-listings-and-ads/js/src/product-feed/index.js](https://github.com/woocommerce/google-listings-and-ads/blob/161f254dc243b6967fbbe78be030d9ba500947a7/js/src/product-feed/index.js#L54)

Line 54 in [161f254](https://github.com/woocommerce/google-listings-and-ads/commit/161f254dc243b6967fbbe78be030d9ba500947a7)

 { canCESPromptOpen && ( 
with:

			{ ( true || canCESPromptOpen ) && (
to force the Customer Effort Score prompt to show up when you navigate to the Product Feed tab.

### Changelog entry

> Tweak - WooCommerce 7.3 Compatibility with Customer Effort Score prompt

### CODE REVIEW

File: js/src/components/customer-effort-score-prompt/index.js [hunk 1]
```diff
@@ -37,6 +37,9 @@ import useEffectRemoveNotice from '.~/hooks/useEffectRemoveNotice';
  * A CustomerEffortScore wrapper that uses tracks to track the selected
  * customer effort score.
  *
+ * TODO: Remove Temoorary fix for WC 7.3 in which adding secondQuestion is required.
```
Comment (tomalec) [inline js/src/components/customer-effort-score-prompt/index.js]: typo :)

```suggestion
 * TODO: Remove temporary fix for WC 7.3 in which adding `secondQuestion` is required.
```

Comment (tomalec) [inline js/src/components/customer-effort-score-prompt/index.js]: We could also use our [compat code comment](https://automatap2.wordpress.com/2022/11/30/legacy-compatibility-code-comment/) 
```suggestion
 * compatibility-code "WC >= 7.3"
 * TODO: Remove temporary fix for WC 7.3 in which adding `secondQuestion` is required.
```

File: js/src/css/shared/_woocommerce-admin.scss [hunk 2]
```diff
@@ -76,3 +76,8 @@
 		}
 	}
 }
+
+// FIX in WC 7.3 for adding margin in the first question label
```
Comment (tomalec) [inline js/src/css/shared/_woocommerce-admin.scss]: WDYT of adding our compatibility code marker?
```suggestion
// compatibility-code "WC >= 7.3" -- adding margin in the first question label.
```

**Review by ianlin — APPROVED** [review]
Thanks for the fix @puntope, I've tested it locally and the CES prompt shows correctly using WC 7.3.0-rc.1.

I've updated the comment to use compatibility code marker per @tomalec suggested. Since woocommerce/woocommerce#36270 is still being reviewed I'm going to merge this PR first so we could release GLA before WC 7.3 is published.

**Comment by puntope** [comment]
Thanks @tomalec and @ianlin  for handling this
