### PR TITLE
Fix the position and the focus/blur behavior of help text for TreeSelectControl

### LINKED ISSUE #1468: Tree Select Control - Help text breaks focus/blur behavior and tree dropdown position.
### Describe the bug:

Adding a help text in the Tree Select controls creates unexpected behaviour in the component. 

https://user-images.githubusercontent.com/5908855/166226588-b5491134-d1e4-4102-a7cd-edb61eff8d36.mov

### Steps to reproduce:

1. Find a section with a helper text in `<SupportedCountrySelect>` for example you can edit `AudienceSection.js `and hardcoding a text in the help prop. 
2. Go to Ad Paid Campaign (or the area of the plugin in which the component with the help text is). 
3. Click on the input, dropdown is expanded but with some extra space.
4. Click outside the input, the dropdown closes.
5. Click on the help text
6. It opens the dropdown
7. Click outside the tree select component, dropdown is not closing. 

### Expected behavior:
- No space between the dropdown and input
- Helper click doesn't affect the dropdown open/closes or the dropdown closes clicking outside if it was opened with the helper. 

### Actual behavior:
- Space between the dropdown and input
- Helper click affect the dropdown open/closes and also the dropdown doesn't close clicking outside if it was opened with the helper. 

### Additional details:

- Introduced in https://github.com/woocommerce/google-listings-and-ads/pull/1421

My suggestion would be to move helper into `<SupportedCountrySelect>` instead of `<TreeSelectControl>`.

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

Closes #1468 

- Move the click event listener that opens the dropdown options from the top container to the Control layer.
- Move the position of help to under the dropdown options.

### Screenshots:

Kapture 2022-05-03 at 12 51 39

### Detailed test instructions:

1. Since there is no existing use case to verify this issue, it suggests adding the `help` prop to the `TreeSelectControl` in the [supported-country-select.js file](https://github.com/woocommerce/google-listings-and-ads/blob/25294743db609a06b62f7819043c9cbc97068346/js/src/components/supported-country-select/supported-country-select.js#L43) as follows when testing.
   ```js
   return (
   	<TreeSelectControl
   		// ... omitted
   		options={ treeOptions }
   		{ ...restProps }
   		help="Can’t find a country? Only supported countries can be selected."
   	/>
   );
   ```
1. Go to the campaign creation page.
1. Click on the country selector to open the dropdown. Check if there is no spacing between the input and dropdown.
1. When the input still has the focus, press ESC key to close the dropdown, and then click on the input. It should open the dropdown.
1. Close the dropdown and click on the help text. It should not open the dropdown.

### Additional details:

Since several control components of `@wordpress/components` and `@wocommerce/components` have the `help` prop and considering TreeSelectControl to be pushed upstream, to make it have a consistent interface, I chose to add in TreeSelectControl when adding `help` before.
- [SelectControl](https://github.com/woocommerce/woocommerce-admin/blob/v2.7.2/packages/components/src/select-control/index.js#L438-L441) (WC)
- [SelectControl](https://github.com/WordPress/gutenberg/tree/%40wordpress/components%4012.0.8/packages/components/src/select-control#help) (WP)
- [CheckboxControl](https://github.com/WordPress/gutenberg/tree/%40wordpress/components%4012.0.8/packages/components/src/checkbox-control#help)
- [RadioControl](https://github.com/WordPress/gutenberg/tree/%40wordpress/components%4012.0.8/packages/components/src/radio-control#help)
- [TextControl](https://github.com/WordPress/gutenberg/tree/%40wordpress/components%4012.0.8/packages/components/src/text-control#help)
- [Form](https://github.com/woocommerce/woocommerce-admin/blob/v2.7.2/packages/components/src/form/index.js#L131) shows error messages via `help` prop

### CODE REVIEW

File: js/src/components/tree-select-control/control.js [hunk 1]
```diff
@@ -36,6 +38,7 @@ const Control = ( {
 	onFocus = () => {},
 	onTagsChange = () => {},
 	onInputChange = () => {},
+	onControlClick = noop,
```
Comment (puntope) [inline js/src/components/tree-select-control/control.js:41]: What is the advantage of `noop` over `() => {}`

To consider using `= () => {},` to maintain consistency as well as no need of lodash dep. (I'm aware we are going to use it anyway in this component, but still)

**Review by puntope — APPROVED** [review]
✅  LGTM

I tested the behaviour and works as expected.

💅  Left some comment regarding the need of `noop` function

File: js/src/components/tree-select-control/control.js (hunk 1 above)
Comment (eason9487) [reply js/src/components/tree-select-control/control.js:41]: > What is the advantage of `noop` over `() => {}`

Usually the differences are not significant, but there are still some reasons I think a named and stable reference `noop` is more appropriate.

- More semantic. `noop` is short for no operations in computer science.
- Avoid unnecessary reference changes.
- Save memory a little bit.

> no need of lodash dep

Not sure if I missed any new updates, I thought this direction was not applied to this repo or the `woocommerce` repo?

Comment (eason9487) [reply js/src/components/tree-select-control/control.js:41]: Oh, I forgot the component were planing to be moved toward

Comment (eason9487) [reply js/src/components/tree-select-control/control.js:41]: Hey @puntope, I'm going to merge this PR. I think we could make the uses of `() => {}` or `noop` consistent for all files of TreeSelectControl in a separate PR.
