### PR TITLE
Fix edit shipping rate modal disappears after auto-save shipping rate in Setup MC

### LINKED ISSUE #1483: Setup MC: Edit shipping rate modal disappears after auto-save shipping rate
### Describe the bug:

In Setup MC, when users have a slow network connection, perform a shipping rate change (and triggers the auto-save mechanism), and click on the edit button to open the edit rate modal, the modal will disappear when the auto-save is completed. 

📹 Demo video of the issue:

https://user-images.githubusercontent.com/417342/167006384-46bf2e3f-42d5-49de-bcda-37fb028c1650.mov

### Steps to reproduce:

1. Open browser dev tools network panel to observe this auto-save shipping rate network call. You can use the dev tools to change the network speed throttling.
2. Go to Setup MC shipping rate section.
3. Change a shipping rate. This should trigger the shipping rate auto-save.
4. Before the auto-save shipping rate API call is completed, open the edit shipping rate modal by clicking on an edit button.

### Expected behavior:

Edit shipping rate modal should not go disappear on its own.

### Actual behavior:

Edit shipping rate modal disappear when the auto-save shipping rate API call is completed.

### Additional details:

This issue came up from PR https://github.com/woocommerce/google-listings-and-ads/pull/1424 when we were doing some code refactor on shipping rate code.

### PR DESCRIPTION
**Pull request by ecgan**
### Changes proposed in this Pull Request:

Closes #1483.

This PR fixes the issue of shipping rate modal disappearing after auto-save in Setup MC. This is done by moving the `EditRateFormModal` back into `ShippingRateInputControl`; it was previously moved out in PR https://github.com/woocommerce/google-listings-and-ads/pull/1424.

### Screenshots:

📹 Demo video:

https://user-images.githubusercontent.com/417342/167009758-7efe7126-339c-454e-8cea-06845eb94b5f.mov

### Detailed test instructions:

1. Open browser dev tools network panel to observe this auto-save shipping rate network call. You can use the dev tools to change the network speed throttling.
2. Go to Setup MC shipping rate section.
3. Change a shipping rate. This should trigger the shipping rate auto-save.
4. Before the auto-save shipping rate API call is completed, open the edit shipping rate modal by clicking on an edit button.
5. When the auto-save shipping rate API call is completed, the edit shipping rate modal should remain open and should not disappear.

### Changelog entry

> Fix - Edit shipping rate modal disappears after auto-save shipping rate in Setup MC.

### CODE REVIEW

File: js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control.js [hunk 1]
```diff
@@ -24,14 +26,16 @@ import './shipping-rate-input-control.scss';
  * This is meant to display an "Edit" button.
  *
  * @param {Object} props
- * @param {JSX.Element} props.labelButton Button to be displayed after the label text.
+ * @param {Array<CountryCode>} props.countryOptions Country options to be passed to EditMinimumOrderFormModal.
```
Comment (eason9487) [inline js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control.js]: 💅  Typo: EditMinimumOrderFormModal

File: js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js [hunk 2]
```diff
@@ -45,33 +45,6 @@ export default function EstimatedShippingRatesCard( {
 		getDeleteHandler,
 	} = getHandlers( { value, onChange } );
 
-	/**
-	 * An Edit button that displays EditRateFormModal to edit shipping rate group upon clicking on the Edit button.
-	 *
-	 * @param {Object} props Props.
-	 * @param {Array<CountryCode>} props.countryOptions Country options to be passed to EditRateFormModal.
-	 * @param {ShippingRateGroup} props.group Shipping rate group to be edited.
```
Comment (eason9487) [inline js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js:53]: 💅  Its `@typedef` could be removed along with it.

https://github.com/woocommerce/google-listings-and-ads/blob/20498e22cd70dacb077fd235b1e851bb17db5793/js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js#L24

**Review by eason9487 — APPROVED** [review]
Tested with 3s delay, and the problem has been fixed. Left two minor things could be adjusted.

File: js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control.js (hunk 1 above)
Comment (ecgan) [reply js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control.js]: Addressed in [`e7d6409` (#1484)](https://github.com/woocommerce/google-listings-and-ads/pull/1484/commits/e7d6409206a2766e756c85328dd5fd7a03612cc1).

File: js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js (hunk 2 above)
Comment (ecgan) [reply js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js:53]: Addressed in [`ca5c929` (#1484)](https://github.com/woocommerce/google-listings-and-ads/pull/1484/commits/ca5c929f69d37d2e9622dcd9e8fb693728dd7bc5).
