### PR TITLE
Fix/1078 shipping values flash during onboarding setup

### LINKED ISSUE #1078: Shipping values flash during the onboarding setup
### Describe the bug:

@layoutd found this issue.

When entering shipping rates/times, sometimes the input values will flash between empty, old value, and new value.

### Expected behavior:

Apart from the currency/number formatting that might change the input value, it should not flash the old/empty value on the `<input>` field after moving out the input cursor.

#### Appear empty value

Screen Capture on 2021-11-02 at 11-10-04

#### Appear old value

Kapture 2021-11-05 at 16 29 48

### Steps to reproduce:

1. Go to step 2 of onboarding setup page.
1. Select "All countries" for audience location.
1. Move to step 3
1. Open browser DevTool and throttle network with "Slow 3G"
    image
1. In step 3, enter values to shipping rates and times quickly, and maybe keep entering values round trip. Then sometimes the flash will happen.

### Additional details:

Eventually the saved values are correct, but it might confuse users.

### PR DESCRIPTION
**Pull request by jorgemd24**
### Changes proposed in this Pull Request:

Closes #1078

### What was causing the issue?

The issue was caused because: 

1. When the Shipping Rate/Shipping Times field is updated, it triggers the API to save the values in the server.  
2. Once the values are saved and the request is finished, the store is updated. 
3. Each input (Shipping Rates & Time Rates) has a useEffect with the following format:

```
const [ value, setValue ] = useState( savedValue );

useEffect( () => {
	setValue( savedValue );
	}, [ savedValue ] );

//Sample of savedValue = { countries:["UK"..] , price: 1 }
```

It should only update the state if the savedValue is updated. I did some debugging and I see that React detects that savedValue is different every time therefore is creating extras re-renderings in both components. This causes that the input gets re-render always with the savedValue instead of the value from the state, consequently showing old data. 

### Proposed solution

This has been resolved updating the useEffect function with the following format: 

	useEffect( () => {
		setValue( savedValue );
	}, [ savedValue.price ] );

	useEffect( () => {
		setValue( savedValue );
	}, [ savedValue.time ] );

In this way we make sure that it should only update the state with the savedValues if the price or time has been updated.

I think we should check other components that can have the same issue and could impact the performance.

With quicker connections, the same issue was happening but it was not visible for the user. 

### Screenshots:

Screen Capture on 2021-12-15 at 17-38-20

### Detailed test instructions:

Visual Testing

1. Go to step 2 of onboarding setup page.
2. Select "All countries" for audience location.
3. Move to step 3
4. Open browser DevTool and throttle network with "Slow 3G"

Unit Tests:

1.  npm run test:js -- countriesTimeInput
2. npm run test:js -- countriesPriceInput

>

### CODE REVIEW

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const CountriesPriceInputForm = ( props ) => {
 
 	useEffect( () => {
 		setValue( savedValue );
-	}, [ savedValue ] );
+	}, [ savedValue.price ] );
```
Comment (ecgan) [inline js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js]: 🚧 React ESLint will complain about this: `"React Hook useEffect has a missing dependency: 'savedValue'. Either include it or remove the dependency array.eslintreact-hooks/exhaustive-deps"`

image

Do you have ESLint extension enabled in your editor? Your editor should be able to help you catch this.

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js [hunk 2]
```diff
@@ -16,7 +16,7 @@ const CountriesTimeInputForm = ( props ) => {
 
 	useEffect( () => {
 		setValue( savedValue );
-	}, [ savedValue ] );
+	}, [ savedValue.time ] );
```
Comment (ecgan) [inline js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js]: 🚧 Same thing, React ESLint will complain about this: `"React Hook useEffect has a missing dependency: 'savedValue'. Either include it or remove the dependency array.eslintreact-hooks/exhaustive-deps"`.

**Review by ecgan — CHANGES_REQUESTED** [review]
Just a quick non-thorough review to add two 🚧 blocker comments below.

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js [hunk 3]
```diff
@@ -0,0 +1,85 @@
+/**
```
Comment (puntope) [inline js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js:1]: Thanks for adding tests. 

❓ 

Is there a reason to have `countriesPriceInput.test.js` and `countriesTimeInput.test.js` in separated files?

All the mocks and external deps are duplicated between both files. I'd consider to use only one file `tests/countriesInput.test.js` and test there both.

Besides the dependencies , the tests themselves are kind of duplicated since both are using same logic

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js (hunk 2 above)
Comment (puntope) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js]: Not judging, just curious!

Why the GH Actions linter is not failing? In theory the GH actions and the linter task should help us to handle this if it's a blocker.

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js (hunk 1 above)
Comment (jorgemd24) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js]: Sorry, I don’t know why my VS code extension didn’t detect it but it is now working 👍 . I have updated the code as well. Commit: [cf03ab5](https://github.com/woocommerce/google-listings-and-ads/commit/cf03ab591744d709d599fbba77cdf6d9a19b2bd5)
 
I would love to discuss a bit more how the props from the CountriesPriceInputForm component are populated. I think the prop `savedValue` should stay immutable if all the values stay the same. I have been looking deeper into the code and I see that the function getCountriesPriceArray is creating a new array every time, therefore, triggering the useEffect and causing the issue that we are trying to resolve. Please let me know your thoughts about this.

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js (hunk 3 above)
Comment (jorgemd24) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js:1]: The idea was to keep different files to make easier the addition of other specific tests for each component. If you like I could join both tests in one file and if we need to add more tests to these components in the future, we could:
 
- Continuing adding the tests in the same file
- Or create a new file depending on the logic and component that we are going to test.

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js (hunk 2 above)
Comment (eason9487) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js]: There's the `--quiet` option in [this workflow](https://github.com/woocommerce/google-listings-and-ads/blob/1.9.0/.github/workflows/js-css-linting.yml#L35) to skip the JS linter warnings. Otherwise, it would show 14 lint warnings by GH annotations in every PR. We could remove the `--quiet` if it's more helpful than the current.

Comment (puntope) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js]: Is not there a way to promote `"React Hook useEffect has a missing dependency...` as error? Since it's a blocker issue. Or on the other side, add annotation somewhere in order to ignore the other warnings and remove `--quiet`

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js (hunk 3 above)
Comment (puntope) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js:1]: Didn't check all the code yet but I can see how `add-rate-modal/useGetRemainingCountryCodes` and `add-time-modal/useGetRemainingCountryCodes`  are duplicated code (only one line changes between them, and name is same actually), same goes with all the files in the modals (add & edit) and maybe more...  (TBD)

This is totally out scope of this issue but feels for me that a refactor is needed here. 

Since I don't wanna block the PR and this is more likely a generalised problem in the component I will open a separated issue regarding the refactor (Including this tests). 

Thoughts?

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js (hunk 2 above)
Comment (eason9487) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js]: > Is not there a way to promote "React Hook useEffect has a missing dependency... as error?

It can be done by changing 'warn' to 'error' here:
https://github.com/woocommerce/google-listings-and-ads/blob/cf03ab591744d709d599fbba77cdf6d9a19b2bd5/.eslintrc.js#L14-L15

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js (hunk 3 above)
Comment (jorgemd24) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js:1]: I agree that shippings-rates & shipping-times are components that seem to have the same logic, consequently, duplicating code and logic. Let's open the issue where we can discuss if it is needed to refactor those two components. Thanks!

File: js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js (hunk 1 above)
Comment (ecgan) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js]: > I think the prop `savedValue` should stay immutable if all the values stay the same.

Just a note, there is a hook to help you do that: https://github.com/woocommerce/google-listings-and-ads/blob/ce120cc0704e8f6fca8e9e90c4c54700f26b69d3/js/src/hooks/useIsEqualRefValue.js. I think you have a point there.

> I have been looking deeper into the code and I see that the function getCountriesPriceArray is creating a new array every time, therefore, triggering the useEffect and causing the issue that we are trying to resolve. Please let me know your thoughts about this.

Thanks for this. I looked deeper and found that you are right. Here's my finding below. 

1. The components hierarchy is like this: `ShippingRateSetup` > `CountriesPriceInputForm` > `CountriesPriceInput`.
2. When users change values in `CountriesPriceInput` and then lose focus on the input, `onBlur` event is triggered. 
3. In the `handleBlur` handler in `CountriesPriceInputForm`, first we call `setValue` which causes state change in `CountriesPriceInputForm`, and trigger re-render (1st re-render of `CountriesPriceInputForm`). 
4. After `setValue`, we call `upsertShippingRates` which will call API and then update wp-data redux state. Because of this state change, anything that uses data from `useShippingRates` will also re-render. The parent component `ShippingRateSetup` uses `useShippingRates`, so it and its children `CountriesPriceInputForm` will re-render (2nd re-render of `CountriesPriceInputForm`).
5. In `CountriesPriceInputForm`, because the `savedValue` props is changed, the `useEffect` would be triggered and call `setValue`, causing a state change and re-render again (3rd re-render of `CountriesPriceInputForm`).

Obviously all these aren't ideal. There are probably other issues which I have not discovered or mentioned above.

I think for the long term goal, we may want to address it as a separate PR, probably under issue https://github.com/woocommerce/google-listings-and-ads/issues/288 (under the "Better implementation" section, about putting shipping rates and shipping times values into Form component and pass them down to child components).

Comment (jorgemd24) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js]: Thanks, @ecgan  for sharing that hook, I have implemented a new solution using useIsEqualRefValue . Please, let me know what are your thoughts about the new changes: [763cfbc](https://github.com/woocommerce/google-listings-and-ads/commit/763cfbcee56165fb454cbf8e3ab02c654f41d63a)

I see that there was already a discussion about “Setup MC Step 3” implementation and that there is some “future work” pending to be addressed that will help us to improve the design and the performance. Thanks for giving me a bit more context about the project 👍

Comment (ecgan) [reply js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js]: @jorgemd24 , 

> I have implemented a new solution using useIsEqualRefValue . Please, let me know what are your thoughts about the new changes: [763cfbc](https://github.com/woocommerce/google-listings-and-ads/commit/763cfbcee56165fb454cbf8e3ab02c654f41d63a)

I think that looks good. 🙂 👍

**Comment by ecgan** [comment]
@jorgemd24 , I tested your solution in this PR here, the solution somewhat helps the issue when users change the values slowly. If they change the values back and forth quickly over slow connections, then we would still see flashing of old values.

📹 See my demo video below with my voice annotation:

https://user-images.githubusercontent.com/417342/146802714-22b5c5c2-5d9c-4237-a175-44060f91fa1b.mov

I think your solution is a good enough as it does somewhat help the issue (_reduce_ the chances of users seeing flashing of old values). To fix the issue completely, I think we would need to work on it in https://github.com/woocommerce/google-listings-and-ads/issues/288 which would require quite a bit of time (not really a "good first issue" as indicated in https://github.com/woocommerce/google-listings-and-ads/issues/1078). I hope I can work on it soon one day.

**Review by ecgan — APPROVED** [review]
Tested, the solution somewhat helps the issue https://github.com/woocommerce/google-listings-and-ads/issues/1078 but not completely, see my demo video in https://github.com/woocommerce/google-listings-and-ads/pull/1157#issuecomment-998102961. All tests passed. 👍 

Given that it somewhat helps the issue for now, I think we are good to go with this PR. For the long term, I think we should look into working on #288.

**Comment by jorgemd24** [comment]
> Tested, the solution somewhat helps the issue #1078 but not completely, see my demo video in [#1157 (comment)](https://github.com/woocommerce/google-listings-and-ads/pull/1157#issuecomment-998102961). All tests passed. 👍
> 
> Given that it somewhat helps the issue for now, I think we are good to go with this PR. For the long term, I think we should look into working on #288.

Thanks, @ecgan, I agree with you that this is a temporal solution. I am sure that with the implementations from #288 we are going to tackle the root of the problem.
