### PR TITLE
Fix retries when deleting products

### LINKED ISSUE #1193: Limit retries when deleting products
This issue is part of the investigation in #1181 

When we sync products we have both the function `handle_update_errors` and `handle_delete_errors`, which will reschedule the action if we encountered an `internalError`. 

When we handle the products to be retried for updating we use the function `ProductHelper::is_sync_failed_recently` to prevent retrying products that failed too many times (5 times within 3 hours).

However for the products that are retried for deleting, we just retry all of them regardless of the failure amount.

Note: In order for this to happen the Google API needs to consistently be returning the `internalError` code. We haven't seen this pattern based on the reports, however Google can return multiple errors, so the question was whether it was one of the errors included in the response which could trigger it to be retried.

### PR DESCRIPTION
**Pull request by mikkamp**
### Changes proposed in this Pull Request:

The task in the initial issue was to limit the amount of retries so if we would receive internal errors it wouldn't endlessly retry. However after additional testing it appears the `can_schedule` will check if there is a scheduled task running with the same hook name and the same list of arguments. When we call the action `woocommerce_gla_batch_retry_delete_products` we are still running the scheduled task with the same hook name. So if all the products in the delete batch fail we will have the same list of arguments and the retry will not be scheduled. This can occur easier if we are only deleting one product at a time (for example when we set a single product to not sync or show, or it goes out of stock).

So this PR changes the following things:
- Always reschedule when we called the action `woocommerce_gla_batch_retry_delete_products`
- Reschedule a retry after 1 minute (no use to retry an internal error right away)
- Limit retries to the product syncer threshold (5 tries)
- Filter the delete ready products when processing the DeleteProducts job, this removes any products that aren't ready (like the ones that reached the failure threshold)
- Add unit tests for the added products

Closes #1193

### Detailed test instructions:

Since we can't simulate internal errors in the Google API's we will need to test this PR with our test proxy in the `delete_error` mode so it can return mocked error responses. If you are using docker see instructions [here](https://github.com/woocommerce/google-listings-and-ads/blob/develop/tests/proxy/proxy.md#connect-test-site-to-proxy) on how to get it running.

1. Run the proxy with a command like: `PROXY_MODE=delete_error cd tests/proxy && npm run test-proxy`
2. Use a code snippet to get our site to connect to the proxy:
```php
define( 'WOOCOMMERCE_GLA_CONNECT_SERVER_URL', 'http://localhost:5500' );
```
3. Connect your Merchant account and sync all or some products (ensure we waited for the syncing to complete)
4. Edit one of the synced products and mark it as "Don't Sync and show" and save it
5. This will trigger a product delete, since we mocked the errors it will trigger a retry until it reaches the threshold of 5
6. Wait for at least 6 minutes till it completes all the retries
7. View the GLA log file in WooCommerce > Status > Logs
8. Confirm that you see 4 failures in the log with a message like (the 5th time it won't be retried so it will only show debug messages that it failed):
```
2022-02-10T08:12:24+00:00 ERROR Automattic\WooCommerce\GoogleListingsAndAds\Product\ProductSyncer::handle_delete_errors Internal API errors while deleting the following products: Array
(
    [online:en:US:gla_1234] => 1234
)
``` 
9. Check in WooCommerce > Status > Scheduled Actions and confirm that we have no more pending actions with the hook `gla/jobs/delete_products/process_item`
10. If we check the completed actions we will see 5 with the hook `gla/jobs/delete_products/process_item`

### Changelog entry
* Fix - Limit failed delete retries to 5 and schedule again after one minute.

### CODE REVIEW

File: src/Product/ProductRepository.php [hunk 1]
```diff
@@ -151,6 +151,22 @@ public function find_sync_ready_products( array $args = [], int $limit = - 1, in
...
+	 *
+	 * @since x.x.x
+	 *
+	 * @param int[] $ids    Array of WooCommerce product IDs
+	 * @param int   $limit  Maximum number of results to retrieve or -1 for unlimited.
+	 * @param int   $offset Amount to offset product results.
+	 *
+	 * @return array
+	 */
+	public function find_delete_product_ids( array $ids, int $limit = - 1, int $offset = 0 ): array {
```
Comment (message-dimke) [inline src/Product/ProductRepository.php:165]: 💅

I looked at `ProductRepository` class, it has methods which do not only find, but also filter and there is a filter dependency added for three methods which are basically `find()` or `find_by_ids()`. Not sure I would do like this. I would think of `DeleteProducts` class as of 'controller' and call `ProductRepository` to find and then filter to filter out products by some criteria, not giving any filter functionality into the ProductRepository itself.

File: src/Jobs/DeleteProducts.php [hunk 2]
```diff
@@ -37,6 +37,11 @@ public function get_name(): string {
 	 * @throws ProductSyncerException If an error occurs. The exception will be logged by ActionScheduler.
 	 */
 	public function process_items( array $product_id_map ) {
+		$ready_ids = $this->product_repository->find_delete_product_ids( $product_id_map );
```
Comment (message-dimke) [inline src/Jobs/DeleteProducts.php:40]: 💅

`find_delete_product_ids` method returns product ids for deletion using product ids for deletion. So it does filtering operation, but inside a Repository type of class, which should, to my opinion, not incorporate filtering and fetch all it finds from the storage by the query it produces. We could 'glue' Repositories and Filters inside Jobs classes.

Some additional thoughts on Repository filtering are here as well: https://github.com/woocommerce/google-listings-and-ads/pull/1238/files#r810348456

File: src/Product/ProductFilter.php [hunk 3]
```diff
@@ -67,4 +67,28 @@ public function filter_sync_ready_products( array $products, bool $return_ids =
...
+	 * Filter and return a list of products that can be deleted.
+	 *
+	 * @since x.x.x
+	 *
+	 * @param WC_Product[] $products
+	 * @param boolean      $return_ids
+	 *
+	 * @return array
+	 */
+	public function filter_products_for_delete( array $products, bool $return_ids = false ): array {
```
Comment (message-dimke) [inline src/Product/ProductFilter.php:81]: 💅

Not sure `$return_ids` is needed here. Method is only used at one single place and returns ids. Filters also filter products, so, maybe, should always return products and then, if you need ids, map to get ids outside of filter. This is still going to be another loop, but same time it is not going to raise the order of complexity.

We could also pass `Helper` as a filtering condition parameter into filter methods instead of class dependency and remove `$return_ids` completely. Besides there seems to be a bug in this class with `filter_sync_ready_products` using `$return_ids` when `woocommerce_gla_get_sync_ready_products_filter` filter expects Product objects, not ids.

https://github.com/woocommerce/google-listings-and-ads/blob/3b2dd688aeaff4cbddce20112e6c159d6e5b3eb4/src/Product/ProductFilter.php#L66

File: src/Product/ProductHelper.php [hunk 4]
```diff
@@ -59,6 +59,7 @@ public function __construct( ProductMetaHandler $meta_handler, WC $wc, MerchantC
 	 * @param GoogleProduct $google_product
 	 */
 	public function mark_as_synced( WC_Product $product, GoogleProduct $google_product ) {
+		$this->meta_handler->delete_failed_delete_attempts( $product );
```
Comment (message-dimke) [inline src/Product/ProductHelper.php:68]: 💅

`delete_failed_delete_attempts` is not about `marking_as_synced` so, maybe, must be moved into its own cleanup delete attempts method and used next to `marking_as_synced` and not inside it? Same thoughts i have on `update_empty_visibility`, which is few lines below.

Or... rename `marking_as_synced` into `cleanup_delete_attempts_mark_as_synced_and_update_empty_visibility` ))

File: src/Product/ProductFilter.php (hunk 3 above)
Comment (message-dimke) [reply src/Product/ProductFilter.php:81]: A small typo here, which is not a part of this PR, or course, but I found it.

https://github.com/woocommerce/google-listings-and-ads/blob/3b2dd688aeaff4cbddce20112e6c159d6e5b3eb4/src/Product/ProductFilter.php#L25

File: src/Product/ProductRepository.php (hunk 1 above)
Comment (mikkamp) [reply src/Product/ProductRepository.php:165]: It sounds like a great idea to separate the functionality, although I'm not sure how practical that would be. I'm not 100% clear on why it was implemented this way, but as far as I understand we need to find a balance between filtering, so it's best to do this at several levels.
The ProductRepository is responsible for filtering based on a DB query, we couldn't move all the filtering functionality into that class, because we would end up with some very expensive DB queries with multiple joins. Neither can we move all the filtering functionality to the ProductFilter class because then we would be retrieving the full product set, and looping through the products one by one, which for a site with 10k products would get excessive.
My intention with this PR was to stick as closely as possible to how it was done for syncing products, if you take a look at the Integration folder you will see several classes for compatible plugins, so I wanted to make it easier to use the a similar structure in case we needed to handle it differently for any of those classes.

File: src/Product/ProductFilter.php (hunk 3 above)
Comment (mikkamp) [reply src/Product/ProductFilter.php:81]: Nice catch, yes it should always be a set of products for that filter. We aren't actually using the filter `woocommerce_gla_get_sync_ready_products_filter` within our plugin (only the pre filter), which is probably why it went unnoticed. I'd suggest to report these two problems in a separate issue, it would be nice to take a deeper look at the unit tests, to see if this could be caught there as well.

File: src/Product/ProductHelper.php (hunk 4 above)
Comment (mikkamp) [reply src/Product/ProductHelper.php:68]: I agree that the cleanup is not part of the syncing, however `mark_as_synced` is called from multiple locations, so we would need a wrapper around that function to call both the mark as sync and the cleanup. I'd sooner rename the function to describe it handles two actions. Although in this case, refactoring that might require quite a bit of additional testing, so I think it's better to update the function comment, to describe what actions it's performing. I'll go ahead and add that.

File: src/Product/ProductFilter.php (hunk 3 above)
Comment (message-dimke) [reply src/Product/ProductFilter.php:81]: Created this one https://github.com/woocommerce/google-listings-and-ads/issues/1259

**Review by message-dimke — APPROVED** [review]
Code works well. Found issues moved into https://github.com/woocommerce/google-listings-and-ads/issues/1259 issue.
