### PR TITLE
Change to require Google Ads connection during the onboarding

### LINKED ISSUE #2172: E2E tests failing
### Describe the bug:
Two e2e tests are currently failing:

Screenshot 2023-12-05 at 17 11 29

Screenshot 2023-12-05 at 17 11 49

### Steps to reproduce:
1. Run E2E tests
2. See failures

### PR DESCRIPTION
**Pull request by eason9487**
### Changes proposed in this Pull Request:

Project thread: pcTzPl-1YY-p2

This PR changes the step 4 of the onboarding:

- Change it to require a connected Google Ads account and make its setup card always visible.
- Hide the content about the ad budget in the Boost card before a Google Ads account is connected.
- Adjust E2E tests to reflect the above changes.
- Extra fix: The E2E util `checkFAQExpandable` doesn't wait for the page to load to proceed with assertions.

It also fixes #2172 as a few related E2E tests failed.

- Cherry-pick ab228ba476f78d15be661086c35410cef5ebc49c
- Fix the budget recommendation test cases in ea809f5597e8a5a6b06c8ec41360e006e283d6d9

Closes #2172 

#### 📹 Connect and disconnect Google Ads, complete onboarding without creating a campaign

https://github.com/woocommerce/google-listings-and-ads/assets/17420811/b39f489c-9994-46fb-adc9-b15bd7b0f3c7

#### 📹 Complete onboarding along with creating a campaign

https://github.com/woocommerce/google-listings-and-ads/assets/17420811/6d1e7ca0-ac2a-4985-997c-0f92eb985e40

#### 📌 Event tracking

💡 Testing this with the UI part together would save some time.

1. Enable event tracking logging by running `localStorage.setItem( 'debug', 'wc-admin:*' )` in the Console tab of DevTool, and refresh page to make it effective.
1. Go to step 4 of the onboarding flow.
1. Test the four buttons that are marked as **A**, **B**, **C**, **D** in the following screenshot.
1. Check if the event names and their properties are the same as the description.

- `gla_onboarding_complete_button_click` for **A** and **C** with these properties:
   - `opened_paid_ads_setup`: yes | no
   - `google_ads_account_status`: connected | disconnected | incomplete
   - `billing_method_status`: unknown | pending | approved | cancelled
   - `campaign_form_validation`: unknown | valid | invalid
   - The unknown status is used when the paid ads setup is not opened.
- `gla_onboarding_open_paid_ads_setup_button_click` for **B**
- `gla_onboarding_complete_with_paid_ads_button_click` for **D**
   - `budget`: should be the same as the entered value
   -  `audiences`: country codes of the campaign audience countries, e.g. `'US,JP,AU'`

#### 📌 UI

1. Go to step 4 of the onboarding flow.
1. During any operations in this onboarding step, the "Google Ads" section should always be shown and it should be above the "Boost product listings with paid ads" section.
1. Before a Google Ads account is connected:
   - The Boost card should only have one feature item and no footer buttons.
      image
   - Check if there is no way to complete the onboarding.
1. After a Google Ads account is created:
   - The Boost card should only have three feature items and footer buttons.
      image
   - Check if the onboarding can be completed without setting up billing.
1. Click the "Create a paid ad campaign" button:
   - Check if the audience and budget UIs are shown and enabled.
1. Disconnect the Google Ads account:
   - Check if the audience and budget UIs are disabled.
   - Check if the "Skip paid ads creation" and "Complete setup" buttons at the bottom of the page are disabled.
1. Connect a Google Ads account.
1. Complete the onboarding with "Skip paid ads creation".
1. Set up audience, budget, and billing. Complete the onboarding with "Complete setup".
1. View the result of E2E tests: https://github.com/woocommerce/google-listings-and-ads/actions/runs/7207930857/job/19635800443

### Changelog entry

> Update - Change to require Google Ads connection during the onboarding.

### CODE REVIEW

File: js/src/components/paid-ads/campaign-preview/mockup-search.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ export default function MockupSearch( { product } ) {
 					</ScaledText>
 					<Placeholder stroke="thinner" width="79" color="blue" />
 				</div>
-				<Flex justfy="space-between" align="stretch">
+				<Flex align="stretch">
```
Comment (eason9487) [inline js/src/components/paid-ads/campaign-preview/mockup-search.js:51]: The "justfy" is a typo. Removed it because the default value of `justify` is already the "space-between".

Ref: https://github.com/WordPress/gutenberg/blob/%40wordpress/components%4019.17.0/packages/components/src/flex/flex/README.md#justify-csspropertiesjustifycontent

**Review by jorgemd24 — APPROVED** [review]
Thanks @eason9487 for working on this, the code looks good and I ran different tests with different scenarios and everything works well. There was one scenario that was not mentioned in the PR but the code manages the situation nicely.

When you try to link an older Ads account without billing set up, the API shows the account as connected (because the[ last incomplete step is not set](https://github.com/woocommerce/google-listings-and-ads/blob/368bb0cc56b3b14e0710b191f8ced33a1e458c0b/src/Ads/AccountService.php#L86)). However, the UI will still prompt the billing setup card, which works fine in this case.

image

Also the E2E tests are now passing 👍
