### PR TITLE
Fix/1205 plugin performance

### LINKED ISSUE #1205: Poor plugin performance
### Describe the bug:
Hi there!

After installing Google Listings & Ads plugin i noticed performance degradation on the site. The TTFB difference is about +200ms when plugin is active and inactive. I have used xdebug profiler to find the bottleneck and found that plugin initialization stage takes from 40% to 60% of runtime.

https://drive.google.com/file/d/163-qbhtoAaktznTLFThx1JMmUu0xTwwF/view?usp=sharing

Thanks for any help.

### PR DESCRIPTION
**Pull request by jorgemd24**
### Changes proposed in this Pull Request:

Closes #1205 

This PR is addressing the issue with  with the function `GoogleAdsFailures::init()` and [protobuf library](https://developers.google.com/protocol-buffers). 
See issue #1205 for more context.

image

The issue was generated because NoteInitializer class was creating an array of `Notes`, including `ReviewAfterClicksNote` & `ReviewAfterConversionsNote` instances. Every instance of `ReviewAfterClicksNote` & `ReviewAfterConversionsNote` needs a `GoogleAdsclient` instance and `GoogleAdsclient`  is calling `GoogleAdsFailures::init()`.

The Notes are used in a scheduled job therefore is not required to load these instances on every request to the website.
To avoid this behaviour we are creating the Notes instances only when the cron job is executed.

### Screenshots:

Cachegrind report using this PR: 
image

### Detailed test instructions:

**How to check that the bottleneck with the Google Ads library has been resolved:**
1. Set xDebug in profile mode.
2. Load the page as a visitor. 
3. Check the cachegrind reports. You should not see that the Google Ads Library is consuming excessive resources. 
It should be similar to the above image.

**How to test that Notes are working:**

1. Set up GLA account.
2. Check that in Tools->Scheduled jobs there is a wc_gla_cron_daily_notes job in the pending tab. If the cron job is not created, deactivate and activate the plugin to trigger the registration again.
3. To force to show one of the notes, add the following transient:
set_transient( 'gla_ads_metrics', [	'clicks' => 20,'conversions' => 20,'impressions' => 20], 3600 ); in plugins_loaded hook in `google-listings-and-ads.php` file. 
4. Go to Tools->Scheduled jobs and run the job manually wc_gla_cron_daily_notes.
5. Go to Woocommerce->Home in the inbox section you should see a new note: “You’ve gotten 20+ conversions through Google Ads! ”

Notes: 

If you already have the Note: “You’ve gotten X+ conversions…” you will need to delete it from the DB. In your DB run `DELETE FROM wp_wc_admin_notes WHERE `name` = 'gla-review-after-conversions';`

### Additional details:

- `GoogleAdsFailures::init()` will still be invoked in the admin page as it is required to use the GoogleAdsClient. 

### Changelog entry

> Fix - Performance issue related with NoteInitializer class.

### CODE REVIEW

File: src/Notes/NoteInitializer.php [hunk 1]
```diff
@@ -70,7 +59,9 @@ public function register(): void {
 	 * Loop through all notes to add any that should be added.
 	 */
 	public function add_notes(): void {
-		foreach ( $this->notes as $note ) {
+		$notes = $this->container->get( Note::class );
```
Comment (mikkamp) [inline src/Notes/NoteInitializer.php:66]: In other classes we have added [a comment at the top](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/src/MerchantCenter/MerchantCenterService.php#L34-L43) showing which classes we retrieve from the container. This makes it easier to see at a glance which dependencies are required for the class.

File: src/Notes/NoteInitializer.php [hunk 2]
```diff
@@ -23,10 +25,10 @@
  *
  * @package Automattic\WooCommerce\GoogleListingsAndAds\Notes
  */
-class NoteInitializer implements Activateable, Deactivateable, InstallableInterface, Service, Registerable {
+class NoteInitializer implements Activateable, Deactivateable, InstallableInterface, Service, Registerable, ContainerAwareInterface {
 
 	use ValidateInterface;
-
+	use ContainerAwareTrait;
```
Comment (mikkamp) [inline src/Notes/NoteInitializer.php]: Probably nicer to leave the blank line in place, but under the `use ContainerAwareTrait` line.

**Review by mikkamp — APPROVED** [review]
Thanks for the improvements. With the profiler running it's a bit slower, but I'm seeing a drop from 1740ms to 680ms. My view looks a bit different then yours, but I can see the Protobuf calls being removed from the top of the list.

Before PR:
image

After PR:
image

It's still showing the container class get call which is resolving classes and it's dependencies. So while I think this is a great change, I still think we should create a followup issue to push it even further. It's also note worthy that a call to the Rest API will still load all the GoogleAds code as well, ex: `GET https://domain.test/wp-json/`

Either way the code in this PR is a great improvement so I'm going to mark it as approved. I tested the note functionality and they are still triggering if the note conditions are met.

**Comment by jorgemd24** [comment]
> It's still showing the container class get call which is resolving classes and it's dependencies. So while I think this is a great change, I still think we should create a followup issue to push it even further.

Do you think that we could limit `maybe_register_services` to only Rest API, scheduled jobs & admin and consequently not calling the container-> get('Services:class') in any other situation?

>It's also note worthy that a call to the Rest API will still load all the GoogleAds code as well, ex: `GET https://domain.test/wp-json/`

Yes, I notice this as well, this happens because the `RestProvider` is registering `CampaignController class` that it's [constructor is using the container to get AdsCampaign::class](https://github.com/woocommerce/google-listings-and-ads/blob/64354cedd3e01562c63f86efe9101c1df569db91/src/API/Site/Controllers/Ads/CampaignController.php#L42) that is using the `GoogleAdsClient`.

We could just load the  `AdsCampaign::class` only when is used in its methods instead of the constructor. Let me know what you think about this and I would be happy to add it to this PR.

**Comment by mikkamp** [comment]
> We could just load the AdsCampaign::class only when is used in its methods instead of the constructor. Let me know what you think about this and I would be happy to add it to this PR.

We've had previous discussions about those patterns, see: pb0Spc-1u4-p2

If we are going to go with any more changes I'd prefer to do them in separate PR's in case we need to revert anything. So in my opinion we'd merge this PR as is, and then do some further research on the next problem.

Personally I think we might benefit from researching a bit more if the code `GoogleAdsFailures::init()` can somehow be called at a later stage instead of directly from the constructor, maybe there is a way to initialize right before a request is sent. Otherwise I get the feeling we are just kicking the can further down the road by preventing constructors from being called.

**Comment by mikkamp** [comment]
> Do you think that we could limit maybe_register_services to only Rest API, scheduled jobs & admin and consequently not calling the container-> get('Services:class') in any other situation?

I would say yes, but I'm not a 100% on exactly which classes are needed in the frontend. So again I'd recommend this in a separate PR so we can properly test the consequences.

File: src/Notes/NoteInitializer.php [hunk 3]
```diff
@@ -12,20 +12,26 @@
...
+use Automattic\WooCommerce\GoogleListingsAndAds\Internal\ContainerAwareTrait;
+use Automattic\WooCommerce\GoogleListingsAndAds\Internal\Interfaces\ContainerAwareInterface;
 use Exception;
 
 defined( 'ABSPATH' ) || exit;
 
 /**
  * NoteInitializer class.
  *
+ *  * ContainerAware used to access:
```
Comment (mikkamp) [inline src/Notes/NoteInitializer.php]: Minor: Just looks like a small copy and paste error with an extra star there.

**Comment by jorgemd24** [comment]
I will create a follow-up issue so we can continue investigating if we can limit the number of dependencies loaded in other scenarios. 

Thanks for the review & comments 👍
