### PR TITLE
Adding update all product test to catch the bug when scheduled job wa…

### LINKED ISSUE #1450: Products are not synced to Google Merchant Center.
### Describe the bug:

The scheduled job is expecting an array of ids, but got an array of WC_Product objects.
https://github.com/woocommerce/google-listings-and-ads/blob/422de5e11115f6bcb2090309bff239f2bd9508e0/src/Jobs/UpdateAllProducts.php#L110

The bug was introduced with this PR https://github.com/woocommerce/google-listings-and-ads/pull/1361 and tests did not catch it. 

### Expected behavior:

The scheduled job to receive product ids instead of objects.

### PR DESCRIPTION
**Pull request by message-dimke**
With PR https://github.com/woocommerce/google-listings-and-ads/pull/1361 an issue was introduced. Scheduled job began to receive item objects instead of object ids and product stopped syncing.

Test did not catch this behaviour and were missing for update all products.

### Changes proposed in this Pull Request:

Adding corresponding tests and fixing the code so the jobs appear working properly again.

Closes #1450.

### Detailed test instructions:

1. Disconnect and connect again creating a new account in Google.
2. You will see in the Product Feed the Status: “Syncing”
3. After a few minutes, I reload the page and I get the Status “Automatically synced to GoogleLast updated: April 26, 2022, 4:22 pm, containing 0 products”

screenshot-2022-04-26-at-16 16 06

screenshot-2022-04-26-at-16 16 10

4. Apply the fix from PR and see products syncing.

### Changelog entry

> Fix - Update all products job syncing products

### CODE REVIEW

File: tests/Unit/Jobs/UpdateAllProductsTest.php [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+	public function setUp(): void {
+		parent::setUp();
+
+		$this->action_scheduler      = $this->createMock( ActionSchedulerInterface::class );
+		$this->monitor               = $this->createMock( ActionSchedulerJobMonitor::class );
+		$this->product_syncer        = $this->createMock( ProductSyncer::class );
+		$this->product_repository    = $this->createMock( ProductRepository::class );
+		$this->product_helper        = $this->createMock( BatchProductHelper::class );
+		$this->merchant_center       = $this->createMock( MerchantCenterService::class );
+		$this->job                   = new UpdateAllProducts(
```
Comment (mikkamp) [inline tests/Unit/Jobs/UpdateAllProductsTest.php]: Just a small note these lines are indented too far.

File: tests/Unit/Jobs/UpdateAllProductsTest.php [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+			->with( $filtered_product_list->get() );
+		$this->product_syncer
+			->method( 'update_by_batch_requests' )
+			->willReturn( $response );
+
+		do_action( self::PROCESS_ITEM_HOOK, $filtered_product_list->get_product_ids() );
+	}
+
+	/**
+	 * Helper function to crate array filled with product mocks for test purposes
```
Comment (mikkamp) [inline tests/Unit/Jobs/UpdateAllProductsTest.php]: Small typo 'create array'

File: tests/Unit/Jobs/UpdateAllProductsTest.php [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+	 *
+	 * @param int $number Number of elements to fill an array with.
+	 * @return WC_Product[]
+	 */
+	private function generate_simple_products_set( int $number ) {
```
Comment (mikkamp) [inline tests/Unit/Jobs/UpdateAllProductsTest.php]: Can we move this to the ProductTrait and indicate in the name that it creates a set of mocked products. Alternatively we also have `create_simple_product_set` in ProductTrait which can be used instead, although it will create "real" products instead of mocked ones.

File: tests/Unit/Jobs/UpdateAllProductsTest.php [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+		$batch_c = new FilteredProductList( [], 0 );
+
+		$this->action_scheduler->expects( $this->exactly( 5 ) )
+			->method( 'schedule_immediate' )
+			->withConsecutive(
+				array( self::CREATE_BATCH_HOOK, [ 1 ] ),
+				array( self::PROCESS_ITEM_HOOK, [ $batch_a->get_product_ids() ] ),
+				array( self::CREATE_BATCH_HOOK, [ 2 ] ),
+				array( self::PROCESS_ITEM_HOOK, [ $batch_b->get_product_ids() ] ),
+				array( self::CREATE_BATCH_HOOK, [ 3 ] ),
```
Comment (mikkamp) [inline tests/Unit/Jobs/UpdateAllProductsTest.php]: can we consistently use the short array syntax. There are several other locations in this file where the long array syntax is used.

File: tests/Unit/Jobs/UpdateAllProductsTest.php [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+		$this->job->schedule();
+
+		do_action( self::CREATE_BATCH_HOOK, 1 );
+		do_action( self::CREATE_BATCH_HOOK, 2 );
+		do_action( self::CREATE_BATCH_HOOK, 3 );
+	}
+
+	public function test_process_item() {
+		$filtered_product_list = new FilteredProductList( $this->generate_simple_products_set( 1 ), 1 );
+		$product_id            = $filtered_product_list->get_product_ids()[0];
```
Comment (mikkamp) [inline tests/Unit/Jobs/UpdateAllProductsTest.php]: This works fine here, but just wanted to mention that we'd need to be careful with this kind of pattern outside of tests. `array_map` preserves the array keys if it's passed only one array, so array key 0 might not always exist especially if some products are filtered out of the list.

**Review by mikkamp — COMMENTED** [review]
Thanks for the code changes, the revised param comments are helpful to explain what we are working with. The initial code changes look good and I see the products are syncing now.

I left a few smaller comments, mainly about the tests, but if we want to cover all of UpdateAllProducts we might need to add a few more tests. Since this has a high priority I'd suggest to do that in a followup PR. Some of the tests we might want to add:

- Filter out some products from the batches and confirm that batches continue even if some batch sizes are smaller or empty, see #861
- Test a final batch smaller than batch size (this will identify that `handle_complete` is not always called, which isn't an issue because we never use it)
- Test `process_items` with an exception

Another thought was that we should call the UpdateAllProducts job on plugin update, like [here](https://github.com/woocommerce/google-listings-and-ads/blob/1.12.5/src/Jobs/Update/PluginUpdate.php#L41-L46). We broke the sync since 1.12.2 so all new users that onboarded after that would have run a "bad" sync. After updating they would need to go through the onboarding process again to retrigger a sync if we don't do it for them.

File: tests/Unit/Jobs/UpdateAllProductsTest.php (hunk 1 above)
Comment (message-dimke) [reply tests/Unit/Jobs/UpdateAllProductsTest.php]: Thanks! Adjusted.

File: tests/Unit/Jobs/UpdateAllProductsTest.php (hunk 3 above)
Comment (message-dimke) [reply tests/Unit/Jobs/UpdateAllProductsTest.php]: Renamed and moved into trait.

File: tests/Unit/Jobs/UpdateAllProductsTest.php (hunk 4 above)
Comment (message-dimke) [reply tests/Unit/Jobs/UpdateAllProductsTest.php]: Thanks! Done. Reformatted into short syntax.

File: tests/Unit/Jobs/UpdateAllProductsTest.php (hunk 5 above)
Comment (message-dimke) [reply tests/Unit/Jobs/UpdateAllProductsTest.php]: Got it

**Comment by message-dimke** [comment]
@mikkamp , I've added exception test on process items to test rescheduling.

**Comment by mikkamp** [comment]
Thanks for adding the additional test, that looks good. Before approving though I'm concerned about the following comment:

> Another thought was that we should call the UpdateAllProducts job on plugin update, like [here](https://github.com/woocommerce/google-listings-and-ads/blob/1.12.5/src/Jobs/Update/PluginUpdate.php#L41-L46). We broke the sync since 1.12.2 so all new users that onboarded after that would have run a "bad" sync. After updating they would need to go through the onboarding process again to retrigger a sync if we don't do it for them.

If we don't address that then we need to provide instructions upon release for the steps that need to be followed to get their products to sync (so I think it would be easier to automate that).

**Review by mikkamp — APPROVED** [review]
Thanks for the additional update procedure. I can confirm that when I bump the version to 1.12.6 the UpdateAllProducts job is run.
